Table dbo.User {
  UserId Int32 [primary key]
  OpenIDClaimedIdentifier String
  OpenIDFriendlyIdentifier String
}

Table dbo.Client {
  ClientId Int32 [primary key]
  ClientIdentifier String
  ClientSecret String
  Callback String
  Name String
  Unknown Int32
}

Table dbo.ClientAuthorization {
  AuthorizationId Int32 [primary key]
  CreatedOnUtc DateTime
  ClientId Int32
  UserId Int32
  Scope String
  ExpirationDateUtc DateTime
}

Table dbo.Nonce {
  Context String [primary key]
  Code String [primary key]
  Timestamp DateTime [primary key]
}

Table  {
  Bucket String [primary key]
  Handle String [primary key]
  ExpiresUtc DateTime
  Secret Byte[]
}

