Table main.films {
  id Int32 [primary key]
  rank Int32
  rating String
  title String
  votes Int32
  year String
}

Table main.films_tree {
  id Int32 [primary key]
  open Int32
  parent Int32
  title String
}

Table main.packages_plain {
  architecture SchemaLoader+UnknownType
  id Int32 [primary key]
  maintainer SchemaLoader+UnknownType
  package SchemaLoader+UnknownType
  priority SchemaLoader+UnknownType
  section SchemaLoader+UnknownType
  size SchemaLoader+UnknownType
  version SchemaLoader+UnknownType
}

Table main.packages_tree {
  has_kids Int32
  hours Int32
  id Int32 [primary key]
  parent_id Int32
  state SchemaLoader+UnknownType
  value SchemaLoader+UnknownType
}

Table main.sqlite_sequence {
  name SchemaLoader+UnknownType
  seq SchemaLoader+UnknownType
}

Table main.sqlite_stat1 {
  idx SchemaLoader+UnknownType
  stat SchemaLoader+UnknownType
  tbl SchemaLoader+UnknownType
}

