Table accounts {
  account_id Int32 [primary key]
  creation_date DateTime
  email_address String
  email_verification_key String
  ops_level Int32
  password_hash String
  salt String
  username String
}

Table characters {
  account_id Int32
  angle Single
  archetype Int32
  character_id Int32 [primary key]
  energy Int32
  game_id Int32
  gender Boolean
  health Int32
  last_ping_time DateTime
  last_sent_event_id Int32
  name String
  new_events_posted Boolean
  picture_id Int32
  power_level Int32
  room_x Int32
  room_y Int32
  room_z Int32
  x Single
  y Single
  z Single
}

Table config {
  app_debug_url String
  app_url String
  client_url String
  email_address String
  email_host String
  email_password String
  email_port Int32
  email_username String
  id Int32 [primary key]
  irc_port Int32
  irc_server String
  version Int32
}

Table energy_tanks {
  energy Int32
  energy_tank_id Int32 [primary key]
  game_id Int32
  ownership Int32
  room_x Int32
  room_y Int32
  room_z Int32
  x Single
  y Single
  z Single
}

Table game_events {
  event_id Int32 [primary key]
  event_time DateTime
  event_type Int32
  game_id Int32
  json_parameters String
}

Table games {
  dungeon_difficulty Int32
  dungeon_size Int32
  game_id Int32 [primary key]
  irc_enabed Boolean
  irc_encryption_enabed Boolean
  irc_encryption_key String
  irc_port Int32
  irc_server String
  name String
  owner_account_id Int32
}

Table loot {
  game_id Int32
  loot_count Int32
  loot_id Int32 [primary key]
  loot_type String
  room_x Int32
  room_y Int32
  room_z Int32
  x Single
  y Single
  z Single
}

Table mobs {
  ai_data String
  angle Single
  energy Int32
  game_id Int32
  health Int32
  mob_id Int32 [primary key]
  mob_type_id Int32
  room_x Int32
  room_y Int32
  room_z Int32
  x Single
  y Single
  z Single
}

Table mob_spawners {
  game_id Int32
  mob_spawner_id Int32 [primary key]
  mob_spawner_table_id Int32
  random_seed Int32
  remaining_spawn_count Int32
  room_x Int32
  room_y Int32
  room_z Int32
  x Single
  y Single
  z Single
}

Table mob_spawn_table_entries {
  mob_spawn_table_entry_id Int32 [primary key]
  mob_spawn_table_id Int32
  reference_id Int32
  reference_is_mob_type Boolean
  weight Int32
}

Table mob_spawn_tables {
  mob_spawn_table_id Int32 [primary key]
  mob_spawn_table_name String
}

Table mob_types {
  mob_type_data String
  mob_type_id Int32 [primary key]
}

Table portals {
  bbox_x0 Single
  bbox_x1 Single
  bbox_y0 Single
  bbox_y1 Single
  game_id Int32
  portal_id Int32 [primary key]
  portal_type Int32
  room_side Int32
  room_x Int32
  room_y Int32
  room_z Int32
  target_portal_id Int32
}

Table rooms {
  game_id Int32
  random_seed Int32
  room_id Int32 [primary key]
  static_data String
  x Int32
  y Int32
  z Int32
}

Table room_templates {
  compressed_nav_mesh Byte[]
  compressed_visibility Byte[]
  id Int32 [primary key]
  name String
  xml String
}

