Table dbo.Dinners {
  DinnerID Int32 [primary key]
  Title String
  EventDate DateTime
  Description String
  HostedBy String
  ContactPhone String
  Address String
  Country String
  Latitude Double
  Longitude Double
}

Table dbo.RSVP {
  RsvpID Int32 [primary key]
  DinnerID Int32
  AttendeeName String
}

