Table "account_payment_gateways" {
  "id" INT [not null]
  "account_id" INT [not null]
  "payment_gateway_id" INT [not null]
  "config" NVARCHAR(255) [not null]
  "deleted_at" DATETIME
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "accounts" {
  "id" INT [not null]
  "first_name" NVARCHAR(255) [not null]
  "last_name" NVARCHAR(255) [not null]
  "email" NVARCHAR(255) [not null]
  "timezone_id" INT
  "date_format_id" INT
  "datetime_format_id" INT
  "currency_id" INT
  "created_at" DATETIME
  "updated_at" DATETIME
  "deleted_at" DATETIME
  "name" NVARCHAR(255)
  "last_ip" NVARCHAR(255)
  "last_login_date" DATETIME
  "address1" NVARCHAR(255)
  "address2" NVARCHAR(255)
  "city" NVARCHAR(255)
  "state" NVARCHAR(255)
  "postal_code" NVARCHAR(255)
  "country_id" INT
  "email_footer" NVARCHAR(255)
  "is_active" TINYINT [not null]
  "is_banned" TINYINT [not null]
  "is_beta" TINYINT [not null]
  "stripe_access_token" NVARCHAR(255)
  "stripe_refresh_token" NVARCHAR(255)
  "stripe_secret_key" NVARCHAR(255)
  "stripe_publishable_key" NVARCHAR(255)
  "stripe_data_raw" NVARCHAR(255)
  "payment_gateway_id" INT [not null]

Indexes {
  id [pk]
}
}

Table "affiliates" {
  "id" INT [not null]
  "name" NVARCHAR(255) [not null]
  "visits" INT [not null]
  "tickets_sold" INT [not null]
  "sales_volume" DECIMAL(8,2) [not null]
  "last_visit" DATETIME [not null]
  "account_id" INT [not null]
  "event_id" INT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
  account_id [name: "affiliates_account_id_index"]
}
}

Table "attendees" {
  "id" INT [not null]
  "order_id" INT [not null]
  "event_id" INT [not null]
  "ticket_id" INT [not null]
  "first_name" NVARCHAR(255) [not null]
  "last_name" NVARCHAR(255) [not null]
  "email" NVARCHAR(255) [not null]
  "private_reference_number" NVARCHAR(255) [not null]
  "created_at" DATETIME
  "updated_at" DATETIME
  "deleted_at" DATETIME
  "is_cancelled" TINYINT [not null]
  "has_arrived" TINYINT [not null]
  "arrival_time" DATETIME
  "account_id" INT [not null]
  "reference_index" INT [not null]
  "is_refunded" TINYINT [not null]

Indexes {
  id [pk]
  order_id [name: "attendees_order_id_index"]
  event_id [name: "attendees_event_id_index"]
  ticket_id [name: "attendees_ticket_id_index"]
  private_reference_number [name: "attendees_private_reference_number_index"]
  account_id [name: "attendees_account_id_index"]
}
}

Table "countries" {
  "id" INT [not null]
  "capital" NVARCHAR(255)
  "citizenship" NVARCHAR(255)
  "country_code" NVARCHAR(255) [not null]
  "currency" NVARCHAR(255)
  "currency_code" NVARCHAR(255)
  "currency_sub_unit" NVARCHAR(255)
  "full_name" NVARCHAR(255)
  "iso_3166_2" NVARCHAR(255) [not null]
  "iso_3166_3" NVARCHAR(255) [not null]
  "name" NVARCHAR(255) [not null]
  "region_code" NVARCHAR(255) [not null]
  "sub_region_code" NVARCHAR(255) [not null]
  "eea" TINYINT [not null]

Indexes {
  id [pk]
}
}

Table "currencies" {
  "id" INT [not null]
  "title" NVARCHAR(255) [not null]
  "symbol_left" NVARCHAR(255) [not null]
  "symbol_right" NVARCHAR(255) [not null]
  "code" NVARCHAR(255) [not null]
  "decimal_place" INT [not null]
  "value" FLOAT [not null]
  "decimal_point" NVARCHAR(255) [not null]
  "thousand_point" NVARCHAR(255) [not null]
  "status" INT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "date_formats" {
  "id" INT [not null]
  "format" NVARCHAR(255) [not null]
  "picker_format" NVARCHAR(255) [not null]
  "label" NVARCHAR(255) [not null]

Indexes {
  id [pk]
}
}

Table "datetime_formats" {
  "id" INT [not null]
  "format" NVARCHAR(255) [not null]
  "picker_format" NVARCHAR(255) [not null]
  "label" NVARCHAR(255) [not null]

Indexes {
  id [pk]
}
}

Table "event_access_codes" {
  "id" INT [not null]
  "event_id" INT [not null]
  "code" NVARCHAR(255) [not null]
  "usage_count" INT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME
  "deleted_at" DATETIME

Indexes {
  id [pk]
}
}

Table "event_images" {
  "id" INT [not null]
  "image_path" NVARCHAR(255) [not null]
  "created_at" DATETIME
  "updated_at" DATETIME
  "event_id" INT [not null]
  "account_id" INT [not null]
  "user_id" INT [not null]

Indexes {
  id [pk]
}
}

Table "event_question" {
  "id" INT [not null]
  "event_id" INT [not null]
  "question_id" INT [not null]

Indexes {
  id [pk]
  event_id [name: "event_question_event_id_index"]
  question_id [name: "event_question_question_id_index"]
}
}

Table "event_stats" {
  "id" INT [not null]
  "date" DATE [not null]
  "views" INT [not null]
  "unique_views" INT [not null]
  "tickets_sold" INT [not null]
  "sales_volume" DECIMAL(8,2) [not null]
  "organiser_fees_volume" DECIMAL(8,2) [not null]
  "event_id" INT [not null]

Indexes {
  id [pk]
  event_id [name: "event_stats_event_id_index"]
}
}

Table "events" {
  "id" INT [not null]
  "title" NVARCHAR(255) [not null]
  "location" NVARCHAR(255)
  "bg_type" NVARCHAR(255) [not null]
  "bg_color" NVARCHAR(255) [not null]
  "bg_image_path" NVARCHAR(255)
  "description" NVARCHAR(255) [not null]
  "start_date" DATETIME
  "end_date" DATETIME
  "on_sale_date" DATETIME
  "account_id" INT [not null]
  "user_id" INT [not null]
  "currency_id" INT
  "sales_volume" DECIMAL(8,2) [not null]
  "organiser_fees_volume" DECIMAL(8,2) [not null]
  "organiser_fee_fixed" DECIMAL(8,2) [not null]
  "organiser_fee_percentage" DECIMAL(8,2) [not null]
  "organiser_id" INT [not null]
  "venue_name" NVARCHAR(255) [not null]
  "venue_name_full" NVARCHAR(255)
  "location_address" NVARCHAR(255)
  "location_address_line_1" NVARCHAR(255) [not null]
  "location_address_line_2" NVARCHAR(255) [not null]
  "location_country" NVARCHAR(255)
  "location_country_code" NVARCHAR(255)
  "location_state" NVARCHAR(255) [not null]
  "location_post_code" NVARCHAR(255) [not null]
  "location_street_number" NVARCHAR(255)
  "location_lat" NVARCHAR(255)
  "location_long" NVARCHAR(255)
  "location_google_place_id" NVARCHAR(255)
  "pre_order_display_message" NVARCHAR(255)
  "post_order_display_message" NVARCHAR(255)
  "social_share_text" NVARCHAR(255)
  "social_show_facebook" TINYINT [not null]
  "social_show_linkedin" TINYINT [not null]
  "social_show_twitter" TINYINT [not null]
  "social_show_email" TINYINT [not null]
  "social_show_googleplus" TINYINT [not null]
  "location_is_manual" INT [not null]
  "is_live" TINYINT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME
  "deleted_at" DATETIME
  "barcode_type" NVARCHAR(255) [not null]
  "ticket_border_color" NVARCHAR(255) [not null]
  "ticket_bg_color" NVARCHAR(255) [not null]
  "ticket_text_color" NVARCHAR(255) [not null]
  "ticket_sub_text_color" NVARCHAR(255) [not null]
  "google_tag_manager_code" NVARCHAR(255)
  "social_show_whatsapp" TINYINT [not null]
  "questions_collection_type" NVARCHAR(255) [not null]
  "checkout_timeout_after" INT [not null]
  "is_1d_barcode_enabled" TINYINT [not null]
  "enable_offline_payments" TINYINT [not null]
  "offline_payment_instructions" NVARCHAR(255)
  "event_image_position" NVARCHAR(255)

Indexes {
  id [pk]
  account_id [name: "events_account_id_index"]
}
}

Table "failed_jobs" {
  "id" INT [not null]
  "connection" NVARCHAR(255) [not null]
  "queue" NVARCHAR(255) [not null]
  "payload" NVARCHAR(255) [not null]
  "failed_at" DATETIME [not null]

Indexes {
  id [pk]
}
}

Table "messages" {
  "id" INT [not null]
  "message" NVARCHAR(255) [not null]
  "subject" NVARCHAR(255) [not null]
  "recipients" NVARCHAR(255)
  "account_id" INT [not null]
  "user_id" INT [not null]
  "event_id" INT [not null]
  "is_sent" INT [not null]
  "sent_at" DATETIME
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
  account_id [name: "messages_account_id_index"]
}
}

Table "order_items" {
  "id" INT [not null]
  "title" NVARCHAR(255) [not null]
  "quantity" INT [not null]
  "unit_price" DECIMAL(8,2) [not null]
  "unit_booking_fee" DECIMAL(8,2)
  "order_id" INT [not null]
  "deleted_at" DATETIME

Indexes {
  id [pk]
}
}

Table "order_statuses" {
  "id" INT [not null]
  "name" NVARCHAR(255) [not null]

Indexes {
  id [pk]
}
}

Table "orders" {
  "id" INT [not null]
  "account_id" INT [not null]
  "order_status_id" INT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME
  "deleted_at" DATETIME
  "first_name" NVARCHAR(255) [not null]
  "last_name" NVARCHAR(255) [not null]
  "email" NVARCHAR(255) [not null]
  "business_name" NVARCHAR(255)
  "business_tax_number" NVARCHAR(255)
  "business_address_line_one" NVARCHAR(255)
  "business_address_line_two" NVARCHAR(255)
  "business_address_state_province" NVARCHAR(255)
  "business_address_city" NVARCHAR(255)
  "ticket_pdf_path" NVARCHAR(255)
  "order_reference" NVARCHAR(255) [not null]
  "transaction_id" NVARCHAR(255)
  "discount" DECIMAL(8,2)
  "booking_fee" DECIMAL(8,2)
  "organiser_booking_fee" DECIMAL(8,2)
  "order_date" DATE
  "notes" NVARCHAR(255)
  "is_deleted" TINYINT [not null]
  "is_cancelled" TINYINT [not null]
  "is_partially_refunded" TINYINT [not null]
  "is_refunded" TINYINT [not null]
  "amount" DECIMAL(8,2) [not null]
  "amount_refunded" DECIMAL(8,2)
  "event_id" INT [not null]
  "payment_gateway_id" INT
  "is_payment_received" TINYINT [not null]
  "is_business" TINYINT [not null]
  "taxamt" FLOAT [not null]
  "business_address_code" NVARCHAR(255)
  "payment_intent" NVARCHAR(255) [not null]

Indexes {
  id [pk]
  account_id [name: "orders_account_id_index"]
  event_id [name: "orders_event_id_index"]
}
}

Table "organisers" {
  "id" INT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME
  "deleted_at" DATETIME
  "account_id" INT [not null]
  "name" NVARCHAR(255) [not null]
  "about" NVARCHAR(255) [not null]
  "email" NVARCHAR(255) [not null]
  "phone" NVARCHAR(255)
  "confirmation_key" NVARCHAR(255) [not null]
  "facebook" NVARCHAR(255) [not null]
  "twitter" NVARCHAR(255) [not null]
  "logo_path" NVARCHAR(255)
  "is_email_confirmed" TINYINT [not null]
  "show_twitter_widget" TINYINT [not null]
  "show_facebook_widget" TINYINT [not null]
  "page_header_bg_color" NVARCHAR(255) [not null]
  "page_bg_color" NVARCHAR(255) [not null]
  "page_text_color" NVARCHAR(255) [not null]
  "enable_organiser_page" TINYINT [not null]
  "google_analytics_code" NVARCHAR(255)
  "google_tag_manager_code" NVARCHAR(255)
  "tax_name" NVARCHAR(255) [not null]
  "tax_value" FLOAT [not null]
  "tax_id" NVARCHAR(255) [not null]
  "charge_tax" TINYINT [not null]

Indexes {
  id [pk]
  account_id [name: "organisers_account_id_index"]
}
}

Table "password_resets" {
  "email" NVARCHAR(255) [not null]
  "token" NVARCHAR(255) [not null]
  "created_at" DATETIME [not null]

Indexes {
  email [name: "password_resets_email_index"]
  token [name: "password_resets_token_index"]
}
}

Table "payment_gateways" {
  "id" INT [not null]
  "provider_name" NVARCHAR(255) [not null]
  "provider_url" NVARCHAR(255) [not null]
  "is_on_site" TINYINT [not null]
  "can_refund" TINYINT [not null]
  "name" NVARCHAR(255) [not null]
  "default" TINYINT [not null]
  "admin_blade_template" NVARCHAR(255) [not null]
  "checkout_blade_template" NVARCHAR(255) [not null]

Indexes {
  id [pk]
}
}

Table "question_answers" {
  "id" INT [not null]
  "attendee_id" INT [not null]
  "event_id" INT [not null]
  "question_id" INT [not null]
  "account_id" INT [not null]
  "answer_text" NVARCHAR(255) [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
  attendee_id [name: "question_answers_attendee_id_index"]
  event_id [name: "question_answers_event_id_index"]
  question_id [name: "question_answers_question_id_index"]
  account_id [name: "question_answers_account_id_index"]
}
}

Table "question_options" {
  "id" INT [not null]
  "name" NVARCHAR(255) [not null]
  "question_id" INT [not null]

Indexes {
  id [pk]
  question_id [name: "question_options_question_id_index"]
}
}

Table "question_ticket" {
  "id" INT [not null]
  "question_id" INT [not null]
  "ticket_id" INT [not null]

Indexes {
  id [pk]
  question_id [name: "question_ticket_question_id_index"]
  ticket_id [name: "question_ticket_ticket_id_index"]
}
}

Table "question_types" {
  "id" INT [not null]
  "alias" NVARCHAR(255) [not null]
  "name" NVARCHAR(255) [not null]
  "has_options" TINYINT [not null]
  "allow_multiple" TINYINT [not null]

Indexes {
  id [pk]
}
}

Table "questions" {
  "id" INT [not null]
  "title" NVARCHAR(255) [not null]
  "question_type_id" INT [not null]
  "account_id" INT [not null]
  "is_required" TINYINT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME
  "deleted_at" DATETIME
  "sort_order" INT [not null]
  "is_enabled" TINYINT [not null]

Indexes {
  id [pk]
  account_id [name: "questions_account_id_index"]
}
}

Table "reserved_tickets" {
  "id" INT [not null]
  "ticket_id" INT [not null]
  "event_id" INT [not null]
  "quantity_reserved" INT [not null]
  "expires" DATETIME [not null]
  "session_id" NVARCHAR(255) [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "ticket_event_access_code" {
  "id" INT [not null]
  "ticket_id" INT [not null]
  "event_access_code_id" INT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "ticket_order" {
  "id" INT [not null]
  "order_id" INT [not null]
  "ticket_id" INT [not null]

Indexes {
  id [pk]
  order_id [name: "ticket_order_order_id_index"]
  ticket_id [name: "ticket_order_ticket_id_index"]
}
}

Table "ticket_statuses" {
  "id" INT [not null]
  "name" NVARCHAR(255) [not null]

Indexes {
  id [pk]
}
}

Table "tickets" {
  "id" INT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME
  "deleted_at" DATETIME
  "edited_by_user_id" INT
  "account_id" INT [not null]
  "order_id" INT
  "event_id" INT [not null]
  "title" NVARCHAR(255) [not null]
  "description" NVARCHAR(255) [not null]
  "price" DECIMAL(8,2) [not null]
  "max_per_person" INT
  "min_per_person" INT
  "quantity_available" INT
  "quantity_sold" INT [not null]
  "start_sale_date" DATETIME
  "end_sale_date" DATETIME
  "sales_volume" DECIMAL(8,2) [not null]
  "organiser_fees_volume" DECIMAL(8,2) [not null]
  "is_paused" TINYINT [not null]
  "public_id" INT
  "user_id" INT [not null]
  "sort_order" INT [not null]
  "is_hidden" TINYINT [not null]

Indexes {
  id [pk]
  account_id [name: "tickets_account_id_index"]
  event_id [name: "tickets_event_id_index"]
  public_id [name: "tickets_public_id_index"]
}
}

Table "timezones" {
  "id" INT [not null]
  "name" NVARCHAR(255) [not null]
  "location" NVARCHAR(255) [not null]

Indexes {
  id [pk]
}
}

Table "users" {
  "id" INT [not null]
  "account_id" INT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME
  "deleted_at" DATETIME
  "first_name" NVARCHAR(255)
  "last_name" NVARCHAR(255)
  "phone" NVARCHAR(255)
  "email" NVARCHAR(255) [not null]
  "password" NVARCHAR(255) [not null]
  "confirmation_code" NVARCHAR(255) [not null]
  "is_registered" TINYINT [not null]
  "is_confirmed" TINYINT [not null]
  "is_parent" TINYINT [not null]
  "remember_token" NVARCHAR(255)
  "api_token" NVARCHAR(255)

Indexes {
  id [pk]
  account_id [name: "users_account_id_index"]
  api_token [unique, name: "users_api_token_unique"]
}
}

Ref "account_payment_gateways_account_id_foreign":"accounts"."id" < "account_payment_gateways"."account_id"

Ref "affiliates_account_id_foreign":"accounts"."id" < "affiliates"."account_id"

Ref "attendees_account_id_foreign":"accounts"."id" < "attendees"."account_id"

Ref "event_images_account_id_foreign":"accounts"."id" < "event_images"."account_id"

Ref "events_account_id_foreign":"accounts"."id" < "events"."account_id"

Ref "messages_account_id_foreign":"accounts"."id" < "messages"."account_id"

Ref "orders_account_id_foreign":"accounts"."id" < "orders"."account_id"

Ref "organisers_account_id_foreign":"accounts"."id" < "organisers"."account_id"

Ref "question_answers_account_id_foreign":"accounts"."id" < "question_answers"."account_id"

Ref "questions_account_id_foreign":"accounts"."id" < "questions"."account_id"

Ref "tickets_account_id_foreign":"accounts"."id" < "tickets"."account_id"

Ref "users_account_id_foreign":"accounts"."id" < "users"."account_id"

Ref "question_answers_attendee_id_foreign":"attendees"."id" < "question_answers"."attendee_id"

Ref "accounts_country_id_foreign":"countries"."id" < "accounts"."country_id"

Ref "accounts_currency_id_foreign":"currencies"."id" < "accounts"."currency_id"

Ref "events_currency_id_foreign":"currencies"."id" < "events"."currency_id"

Ref "accounts_date_format_id_foreign":"date_formats"."id" < "accounts"."date_format_id"

Ref "accounts_datetime_format_id_foreign":"datetime_formats"."id" < "accounts"."datetime_format_id"

Ref "ticket_event_access_code_event_access_code_id_foreign":"event_access_codes"."id" < "ticket_event_access_code"."event_access_code_id"

Ref "affiliates_event_id_foreign":"events"."id" < "affiliates"."event_id"

Ref "attendees_event_id_foreign":"events"."id" < "attendees"."event_id"

Ref "event_access_codes_event_id_foreign":"events"."id" < "event_access_codes"."event_id"

Ref "event_images_event_id_foreign":"events"."id" < "event_images"."event_id"

Ref "event_question_event_id_foreign":"events"."id" < "event_question"."event_id"

Ref "event_stats_event_id_foreign":"events"."id" < "event_stats"."event_id"

Ref "messages_event_id_foreign":"events"."id" < "messages"."event_id"

Ref "orders_event_id_foreign":"events"."id" < "orders"."event_id"

Ref "question_answers_event_id_foreign":"events"."id" < "question_answers"."event_id"

Ref "reserved_tickets_event_id_foreign":"events"."id" < "reserved_tickets"."event_id"

Ref "tickets_event_id_foreign":"events"."id" < "tickets"."event_id"

Ref "orders_order_status_id_foreign":"order_statuses"."id" < "orders"."order_status_id"

Ref "attendees_order_id_foreign":"orders"."id" < "attendees"."order_id"

Ref "order_items_order_id_foreign":"orders"."id" < "order_items"."order_id"

Ref "ticket_order_order_id_foreign":"orders"."id" < "ticket_order"."order_id"

Ref "tickets_order_id_foreign":"orders"."id" < "tickets"."order_id"

Ref "events_organiser_id_foreign":"organisers"."id" < "events"."organiser_id"

Ref "account_payment_gateways_payment_gateway_id_foreign":"payment_gateways"."id" < "account_payment_gateways"."payment_gateway_id"

Ref "accounts_payment_gateway_id_foreign":"payment_gateways"."id" < "accounts"."payment_gateway_id"

Ref "orders_payment_gateway_id_foreign":"payment_gateways"."id" < "orders"."payment_gateway_id"

Ref "questions_question_type_id_foreign":"question_types"."id" < "questions"."question_type_id"

Ref "event_question_question_id_foreign":"questions"."id" < "event_question"."question_id"

Ref "question_answers_question_id_foreign":"questions"."id" < "question_answers"."question_id"

Ref "question_options_question_id_foreign":"questions"."id" < "question_options"."question_id"

Ref "question_ticket_question_id_foreign":"questions"."id" < "question_ticket"."question_id"

Ref "attendees_ticket_id_foreign":"tickets"."id" < "attendees"."ticket_id"

Ref "question_ticket_ticket_id_foreign":"tickets"."id" < "question_ticket"."ticket_id"

Ref "reserved_tickets_ticket_id_foreign":"tickets"."id" < "reserved_tickets"."ticket_id"

Ref "ticket_event_access_code_ticket_id_foreign":"tickets"."id" < "ticket_event_access_code"."ticket_id"

Ref "ticket_order_ticket_id_foreign":"tickets"."id" < "ticket_order"."ticket_id"

Ref "accounts_timezone_id_foreign":"timezones"."id" < "accounts"."timezone_id"

Ref "event_images_user_id_foreign":"users"."id" < "event_images"."user_id"

Ref "events_user_id_foreign":"users"."id" < "events"."user_id"

Ref "messages_user_id_foreign":"users"."id" < "messages"."user_id"

Ref "tickets_user_id_foreign":"users"."id" < "tickets"."user_id"
