Table "bootstrap4_alerts_bootstrap4alerts" {
  "cmsplugin_ptr_id" INT [not null]
  "alert_context" NVARCHAR(255) [not null]
  "alert_dismissable" TINYINT [not null]
  "tag_type" NVARCHAR(255) [not null]
  "attributes" NVARCHAR(255) [not null]

Indexes {
  cmsplugin_ptr_id [pk]
}
}

Table "bootstrap4_badge_bootstrap4badge" {
  "cmsplugin_ptr_id" INT [not null]
  "badge_text" NVARCHAR(255) [not null]
  "badge_context" NVARCHAR(255) [not null]
  "badge_pills" TINYINT [not null]
  "attributes" NVARCHAR(255) [not null]

Indexes {
  cmsplugin_ptr_id [pk]
}
}

Table "bootstrap4_card_bootstrap4card" {
  "cmsplugin_ptr_id" INT [not null]
  "card_type" NVARCHAR(255) [not null]
  "card_context" NVARCHAR(255) [not null]
  "card_alignment" NVARCHAR(255) [not null]
  "card_outline" TINYINT [not null]
  "card_text_color" NVARCHAR(255) [not null]
  "tag_type" NVARCHAR(255) [not null]
  "attributes" NVARCHAR(255) [not null]

Indexes {
  cmsplugin_ptr_id [pk]
}
}

Table "bootstrap4_card_bootstrap4cardinner" {
  "cmsplugin_ptr_id" INT [not null]
  "inner_type" NVARCHAR(255) [not null]
  "tag_type" NVARCHAR(255) [not null]
  "attributes" NVARCHAR(255) [not null]

Indexes {
  cmsplugin_ptr_id [pk]
}
}

Table "bootstrap4_carousel_bootstrap4carousel" {
  "cmsplugin_ptr_id" INT [not null]
  "template" NVARCHAR(255) [not null]
  "carousel_interval" INT [not null]
  "carousel_controls" TINYINT [not null]
  "carousel_indicators" TINYINT [not null]
  "carousel_keyboard" TINYINT [not null]
  "carousel_pause" NVARCHAR(255) [not null]
  "carousel_ride" NVARCHAR(255) [not null]
  "carousel_wrap" TINYINT [not null]
  "tag_type" NVARCHAR(255) [not null]
  "attributes" NVARCHAR(255) [not null]
  "carousel_aspect_ratio" NVARCHAR(255) [not null]

Indexes {
  cmsplugin_ptr_id [pk]
}
}

Table "bootstrap4_carousel_bootstrap4carouselslide" {
  "template" NVARCHAR(255) [not null]
  "name" NVARCHAR(255) [not null]
  "external_link" NVARCHAR(255) [not null]
  "anchor" NVARCHAR(255) [not null]
  "mailto" NVARCHAR(255) [not null]
  "phone" NVARCHAR(255) [not null]
  "target" NVARCHAR(255) [not null]
  "attributes" NVARCHAR(255) [not null]
  "cmsplugin_ptr_id" INT [not null]
  "carousel_content" NVARCHAR(255) [not null]
  "tag_type" NVARCHAR(255) [not null]
  "carousel_image_id" INT
  "internal_link_id" INT
  "file_link_id" INT

Indexes {
  cmsplugin_ptr_id [pk]
  carousel_image_id [name: "bootstrap4_carousel_bootstrap4carouselslide_carousel_image_id_index"]
  internal_link_id [name: "bootstrap4_carousel_bootstrap4carouselslide_internal_link_id_index"]
  file_link_id [name: "bootstrap4_carousel_bootstrap4carouselslide_file_link_id_index"]
}
}

Table "bootstrap4_collapse_bootstrap4collapse" {
  "cmsplugin_ptr_id" INT [not null]
  "siblings" NVARCHAR(255) [not null]
  "tag_type" NVARCHAR(255) [not null]
  "attributes" NVARCHAR(255) [not null]

Indexes {
  cmsplugin_ptr_id [pk]
}
}

Table "bootstrap4_collapse_bootstrap4collapsecontainer" {
  "cmsplugin_ptr_id" INT [not null]
  "identifier" NVARCHAR(255) [not null]
  "tag_type" NVARCHAR(255) [not null]
  "attributes" NVARCHAR(255) [not null]

Indexes {
  cmsplugin_ptr_id [pk]
  identifier [name: "bootstrap4_collapse_bootstrap4collapsecontainer_identifier_index"]
}
}

Table "bootstrap4_collapse_bootstrap4collapsetrigger" {
  "cmsplugin_ptr_id" INT [not null]
  "identifier" NVARCHAR(255) [not null]
  "tag_type" NVARCHAR(255) [not null]
  "attributes" NVARCHAR(255) [not null]

Indexes {
  cmsplugin_ptr_id [pk]
  identifier [name: "bootstrap4_collapse_bootstrap4collapsetrigger_identifier_index"]
}
}

Table "bootstrap4_content_bootstrap4blockquote" {
  "cmsplugin_ptr_id" INT [not null]
  "quote_content" NVARCHAR(255) [not null]
  "quote_origin" NVARCHAR(255) [not null]
  "quote_alignment" NVARCHAR(255) [not null]
  "attributes" NVARCHAR(255) [not null]

Indexes {
  cmsplugin_ptr_id [pk]
}
}

Table "bootstrap4_content_bootstrap4code" {
  "cmsplugin_ptr_id" INT [not null]
  "code_content" NVARCHAR(255) [not null]
  "tag_type" NVARCHAR(255) [not null]
  "attributes" NVARCHAR(255) [not null]

Indexes {
  cmsplugin_ptr_id [pk]
}
}

Table "bootstrap4_content_bootstrap4figure" {
  "cmsplugin_ptr_id" INT [not null]
  "figure_caption" NVARCHAR(255) [not null]
  "figure_alignment" NVARCHAR(255) [not null]
  "attributes" NVARCHAR(255) [not null]

Indexes {
  cmsplugin_ptr_id [pk]
}
}

Table "bootstrap4_grid_bootstrap4gridcolumn" {
  "cmsplugin_ptr_id" INT [not null]
  "column_type" NVARCHAR(255) [not null]
  "column_alignment" NVARCHAR(255) [not null]
  "tag_type" NVARCHAR(255) [not null]
  "attributes" NVARCHAR(255) [not null]
  "xs_col" INT
  "xs_order" INT
  "xs_ml" TINYINT [not null]
  "xs_mr" TINYINT [not null]
  "sm_col" INT
  "sm_order" INT
  "sm_ml" TINYINT [not null]
  "sm_mr" TINYINT [not null]
  "md_col" INT
  "md_order" INT
  "md_ml" TINYINT [not null]
  "md_mr" TINYINT [not null]
  "lg_col" INT
  "lg_order" INT
  "lg_ml" TINYINT [not null]
  "lg_mr" TINYINT [not null]
  "xl_col" INT
  "xl_order" INT
  "xl_ml" TINYINT [not null]
  "xl_mr" TINYINT [not null]
  "lg_offset" INT
  "md_offset" INT
  "sm_offset" INT
  "xl_offset" INT
  "xs_offset" INT

Indexes {
  cmsplugin_ptr_id [pk]
}
}

Table "bootstrap4_grid_bootstrap4gridcontainer" {
  "cmsplugin_ptr_id" INT [not null]
  "container_type" NVARCHAR(255) [not null]
  "tag_type" NVARCHAR(255) [not null]
  "attributes" NVARCHAR(255) [not null]

Indexes {
  cmsplugin_ptr_id [pk]
}
}

Table "bootstrap4_grid_bootstrap4gridrow" {
  "cmsplugin_ptr_id" INT [not null]
  "vertical_alignment" NVARCHAR(255) [not null]
  "horizontal_alignment" NVARCHAR(255) [not null]
  "gutters" TINYINT [not null]
  "tag_type" NVARCHAR(255) [not null]
  "attributes" NVARCHAR(255) [not null]

Indexes {
  cmsplugin_ptr_id [pk]
}
}

Table "bootstrap4_jumbotron_bootstrap4jumbotron" {
  "cmsplugin_ptr_id" INT [not null]
  "fluid" TINYINT [not null]
  "tag_type" NVARCHAR(255) [not null]
  "attributes" NVARCHAR(255) [not null]

Indexes {
  cmsplugin_ptr_id [pk]
}
}

Table "bootstrap4_link_bootstrap4link" {
  "template" NVARCHAR(255) [not null]
  "name" NVARCHAR(255) [not null]
  "external_link" NVARCHAR(255) [not null]
  "anchor" NVARCHAR(255) [not null]
  "mailto" NVARCHAR(255) [not null]
  "phone" NVARCHAR(255) [not null]
  "target" NVARCHAR(255) [not null]
  "attributes" NVARCHAR(255) [not null]
  "cmsplugin_ptr_id" INT [not null]
  "link_type" NVARCHAR(255) [not null]
  "link_context" NVARCHAR(255) [not null]
  "link_size" NVARCHAR(255) [not null]
  "link_outline" TINYINT [not null]
  "link_block" TINYINT [not null]
  "internal_link_id" INT
  "icon_left" NVARCHAR(255) [not null]
  "icon_right" NVARCHAR(255) [not null]
  "file_link_id" INT

Indexes {
  cmsplugin_ptr_id [pk]
  internal_link_id [name: "bootstrap4_link_bootstrap4link_internal_link_id_index"]
  file_link_id [name: "bootstrap4_link_bootstrap4link_file_link_id_index"]
}
}

Table "bootstrap4_listgroup_bootstrap4listgroup" {
  "cmsplugin_ptr_id" INT [not null]
  "list_group_flush" TINYINT [not null]
  "tag_type" NVARCHAR(255) [not null]
  "attributes" NVARCHAR(255) [not null]

Indexes {
  cmsplugin_ptr_id [pk]
}
}

Table "bootstrap4_listgroup_bootstrap4listgroupitem" {
  "cmsplugin_ptr_id" INT [not null]
  "list_context" NVARCHAR(255) [not null]
  "list_state" NVARCHAR(255) [not null]
  "tag_type" NVARCHAR(255) [not null]
  "attributes" NVARCHAR(255) [not null]

Indexes {
  cmsplugin_ptr_id [pk]
}
}

Table "bootstrap4_media_bootstrap4media" {
  "cmsplugin_ptr_id" INT [not null]
  "tag_type" NVARCHAR(255) [not null]
  "attributes" NVARCHAR(255) [not null]

Indexes {
  cmsplugin_ptr_id [pk]
}
}

Table "bootstrap4_media_bootstrap4mediabody" {
  "cmsplugin_ptr_id" INT [not null]
  "tag_type" NVARCHAR(255) [not null]
  "attributes" NVARCHAR(255) [not null]

Indexes {
  cmsplugin_ptr_id [pk]
}
}

Table "bootstrap4_picture_bootstrap4picture" {
  "template" NVARCHAR(255) [not null]
  "external_picture" NVARCHAR(255)
  "width" INT
  "height" INT
  "alignment" NVARCHAR(255) [not null]
  "caption_text" NVARCHAR(255)
  "attributes" NVARCHAR(255) [not null]
  "link_url" NVARCHAR(255)
  "link_target" NVARCHAR(255) [not null]
  "link_attributes" NVARCHAR(255) [not null]
  "use_automatic_scaling" TINYINT [not null]
  "use_no_cropping" TINYINT [not null]
  "use_crop" TINYINT [not null]
  "use_upscale" TINYINT [not null]
  "cmsplugin_ptr_id" INT [not null]
  "picture_fluid" TINYINT [not null]
  "picture_rounded" TINYINT [not null]
  "picture_thumbnail" TINYINT [not null]
  "link_page_id" INT
  "picture_id" INT
  "thumbnail_options_id" INT
  "use_responsive_image" NVARCHAR(255) [not null]

Indexes {
  cmsplugin_ptr_id [pk]
  link_page_id [name: "bootstrap4_picture_bootstrap4picture_link_page_id_index"]
  picture_id [name: "bootstrap4_picture_bootstrap4picture_picture_id_index"]
  thumbnail_options_id [name: "bootstrap4_picture_bootstrap4picture_thumbnail_options_id_index"]
}
}

Table "bootstrap4_tabs_bootstrap4tab" {
  "cmsplugin_ptr_id" INT [not null]
  "template" NVARCHAR(255) [not null]
  "tab_type" NVARCHAR(255) [not null]
  "tab_alignment" NVARCHAR(255) [not null]
  "tab_index" INT
  "tab_effect" NVARCHAR(255) [not null]
  "tag_type" NVARCHAR(255) [not null]
  "attributes" NVARCHAR(255) [not null]

Indexes {
  cmsplugin_ptr_id [pk]
}
}

Table "bootstrap4_tabs_bootstrap4tabitem" {
  "cmsplugin_ptr_id" INT [not null]
  "tab_title" NVARCHAR(255) [not null]
  "tag_type" NVARCHAR(255) [not null]
  "attributes" NVARCHAR(255) [not null]

Indexes {
  cmsplugin_ptr_id [pk]
}
}

Table "bootstrap4_utilities_bootstrap4spacing" {
  "cmsplugin_ptr_id" INT [not null]
  "space_property" NVARCHAR(255) [not null]
  "space_sides" NVARCHAR(255) [not null]
  "space_size" NVARCHAR(255) [not null]
  "space_device" NVARCHAR(255) [not null]
  "tag_type" NVARCHAR(255) [not null]
  "attributes" NVARCHAR(255) [not null]

Indexes {
  cmsplugin_ptr_id [pk]
}
}

Table "cms_cmsplugin" {
  "id" INT [not null]

Indexes {
  id [pk]
}
}

Table "cms_page" {
  "id" INT [not null]

Indexes {
  id [pk]
}
}

Table "filer_file" {
  "id" INT [not null]

Indexes {
  id [pk]
}
}

Table "filer_image" {
  "id" INT [not null]

Indexes {
  id [pk]
}
}

Table "filer_thumbmailoption" {
  "id" INT [not null]

Indexes {
  id [pk]
}
}

Ref "bootstrap4_carousel_bootstrap4carouselslide_carousel_image_id_foreign":"filer_image"."id" < "bootstrap4_carousel_bootstrap4carouselslide"."carousel_image_id"

Ref "bootstrap4_carousel_bootstrap4carouselslide_internal_link_id_foreign":"cms_page"."id" < "bootstrap4_carousel_bootstrap4carouselslide"."internal_link_id"

Ref "bootstrap4_carousel_bootstrap4carouselslide_file_link_id_foreign":"filer_file"."id" < "bootstrap4_carousel_bootstrap4carouselslide"."file_link_id"

Ref "bootstrap4_link_bootstrap4link_internal_link_id_foreign":"cms_page"."id" < "bootstrap4_link_bootstrap4link"."internal_link_id"

Ref "bootstrap4_link_bootstrap4link_file_link_id_foreign":"filer_file"."id" < "bootstrap4_link_bootstrap4link"."file_link_id"

Ref "bootstrap4_picture_bootstrap4picture_link_page_id_foreign":"cms_page"."id" < "bootstrap4_picture_bootstrap4picture"."link_page_id"

Ref "bootstrap4_picture_bootstrap4picture_picture_id_foreign":"filer_image"."id" < "bootstrap4_picture_bootstrap4picture"."picture_id"

Ref "bootstrap4_picture_bootstrap4picture_thumbnail_options_id_foreign":"filer_thumbmailoption"."id" < "bootstrap4_picture_bootstrap4picture"."thumbnail_options_id"
