Table "actions" {
  "id" BIGINT [not null]
  "user_id" BIGINT
  "query" TEXT
  "actions" TEXT
  "feed_ids" TEXT
  "all_feeds" BOOLEAN [not null]
  "created_at" timestamp(0)
  "updated_at" timestamp(0)
  "title" TEXT
  "tag_ids" BIGINT
  "action_type" BIGINT
  "computed_feed_ids" BIGINT
  "status" BIGINT
}

Table "authentication_tokens" {
  "id" BIGINT [not null]
  "user_id" BIGINT [not null]
  "token" TEXT [not null]
  "purpose" INTEGER [not null]
  "data" jsonb
  "created_at" timestamp(0) [not null]
  "updated_at" timestamp(0) [not null]
  "active" BOOLEAN [not null]

Indexes {
  (purpose, token, active) [name: "authentication_tokens_purpose_token_active_index"]
  user_id [name: "authentication_tokens_user_id_index"]
}
}

Table "billing_events" {
  "id" BIGINT [not null]
  "details" TEXT
  "event_type" VARCHAR(255)
  "billable_id" BIGINT
  "billable_type" VARCHAR(255)
  "created_at" timestamp(0) [not null]
  "updated_at" timestamp(0) [not null]
  "event_id" VARCHAR(255) [not null]
  "info" jsonb [not null]

Indexes {
  (billable_id, billable_type) [name: "billing_events_billable_id_billable_type_index"]
}
}

Table "coupons" {
  "id" BIGINT [not null]
  "user_id" BIGINT
  "coupon_code" VARCHAR(255)
  "sent_to" VARCHAR(255)
  "redeemed" BOOLEAN
  "created_at" timestamp(0) [not null]
  "updated_at" timestamp(0) [not null]

Indexes {
  user_id [name: "coupons_user_id_index"]
}
}

Table "deleted_users" {
  "id" BIGINT [not null]
  "email" TEXT
  "customer_id" TEXT
  "created_at" timestamp(0) [not null]
  "updated_at" timestamp(0) [not null]

Indexes {
  email [name: "deleted_users_email_index"]
}
}

Table "devices" {
  "id" BIGINT [not null]
  "user_id" BIGINT
  "token" TEXT
  "model" TEXT
  "device_type" BIGINT
  "created_at" timestamp(0) [not null]
  "updated_at" timestamp(0) [not null]
  "operating_system" TEXT [not null]

Indexes {
  user_id [name: "devices_user_id_index"]
}
}

Table "entries" {
  "id" BIGINT [not null]
  "feed_id" BIGINT
  "title" TEXT
  "url" TEXT
  "author" TEXT
  "summary" TEXT
  "content" TEXT
  "published" timestamp(0) [not null]
  "updated" timestamp(0) [not null]
  "created_at" timestamp(0) [not null]
  "updated_at" timestamp(0) [not null]
  "entry_id" TEXT
  "public_id" VARCHAR(255)
  "old_public_id" VARCHAR(255)
  "starred_entreis_count" BIGINT [not null]
  "data" JSON
  "original" json
  "source" TEXT
  "image_url" TEXT
  "processed_image_url" TEXT
  "image" JSON
  "recently_played_entries_count" BIGINT
  "thread_id" BIGINT
  "settings" jsonb

Indexes {
  feed_id [name: "entries_feed_id_index"]
  thread_id [name: "entries_thread_id_index"]
}
}

Table "favicons" {
  "id" BIGINT [not null]
  "host" TEXT
  "favicon" TEXT
  "created_at" timestamp(0) [not null]
  "updated_at" timestamp(0) [not null]
  "data" JSON
  "url" VARCHAR(255)
}

Table "feed_stats" {
  "id" BIGINT [not null]
  "feed_id" BIGINT
  "day" DATE
  "entries_count" BIGINT
  "created_at" timestamp(0) [not null]
  "updated_at" timestamp(0) [not null]

Indexes {
  (feed_id, day) [name: "feed_stats_feed_id_day_index"]
  feed_id [name: "feed_stats_feed_id_index"]
}
}

Table "feeds" {
  "id" BIGINT [not null]
  "title" TEXT
  "feed_url" TEXT
  "site_url" TEXT
  "etag" TEXT
  "created_at" timestamp(0) [not null]
  "updated_at" timestamp(0) [not null]
  "last_modified" timestamp(0)
  "subscriptions_count" BIGINT [not null]
  "protected" BOOLEAN [not null]
  "push_expiration" timestamp(0)
  "last_published_entry" timestamp(0)
  "host" TEXT
  "self_url" TEXT
  "feed_type" BIGINT
  "active" BOOLEAN [not null]
  "options" JSON

Indexes {
  last_published_entry [name: "feeds_last_published_entry_index"]
  host [name: "feeds_host_index"]
  feed_type [name: "feeds_feed_type_index"]
  active [name: "feeds_active_index"]
}
}

Table "import_items" {
  "id" BIGINT [not null]
  "import_id" BIGINT
  "details" TEXT
  "created_at" timestamp(0) [not null]
  "updated_at" timestamp(0) [not null]
  "item_type" VARCHAR(255)
  "status" BIGINT [not null]

Indexes {
  (import_id, status) [name: "import_items_import_id_status_index"]
  import_id [name: "import_items_import_id_index"]
}
}

Table "imports" {
  "id" BIGINT [not null]
  "user_id" BIGINT
  "complete" BOOLEAN
  "created_at" timestamp(0) [not null]
  "updated_at" timestamp(0) [not null]
  "upload" VARCHAR(255)
}

Table "in_app_purchases" {
  "id" BIGINT [not null]
  "user_id" BIGINT
  "transaction_id" TEXT
  "purchase_date" timestamp(0)
  "receipt" JSON
  "created_at" timestamp(0)
  "updated_at" timestamp(0)
  "response" JSON

Indexes {
  user_id [name: "in_app_purchases_user_id_index"]
}
}

Table "newsletter_senders" {
  "id" BIGINT [not null]
  "feed_id" BIGINT [not null]
  "active" BOOLEAN [not null]
  "token" TEXT [not null]
  "full_token" TEXT [not null]
  "email" TEXT [not null]
  "name" TEXT
  "created_at" timestamp(0) [not null]
  "updated_at" timestamp(0) [not null]

Indexes {
  token [name: "newsletter_senders_token_index"]
}
}

Table "plans" {
  "id" BIGINT [not null]
  "stripe_id" VARCHAR(255)
  "name" VARCHAR(255)
  "price" INTEGER [not null]
  "created_at" timestamp(0) [not null]
  "updated_at" timestamp(0) [not null]
  "price_tier" BIGINT
}

Table "recently_played_entries" {
  "id" BIGINT [not null]
  "user_id" BIGINT [not null]
  "entry_id" BIGINT [not null]
  "progress" BIGINT [not null]
  "duration" BIGINT [not null]
  "created_at" timestamp(0) [not null]
  "updated_at" timestamp(0) [not null]

Indexes {
  (user_id, created_at) [name: "recently_played_entries_user_id_created_at_index"]
  user_id [name: "recently_played_entries_user_id_index"]
  entry_id [name: "recently_played_entries_entry_id_index"]
}
}

Table "recently_read_entries" {
  "id" BIGINT [not null]
  "user_id" BIGINT
  "entry_id" BIGINT
  "created_at" timestamp(0)
  "updated_at" timestamp(0)

Indexes {
  (user_id, id) [name: "recently_read_entries_user_id_id_index"]
  user_id [name: "recently_read_entries_user_id_index"]
  entry_id [name: "recently_read_entries_entry_id_index"]
  created_at [name: "recently_read_entries_created_at_index"]
}
}

Table "saved_searches" {
  "id" BIGINT [not null]
  "user_id" BIGINT [not null]
  "name" TEXT [not null]
  "query" TEXT
  "created_at" timestamp(0)
  "updated_at" timestamp(0)

Indexes {
  user_id [name: "saved_searches_user_id_index"]
}
}

Table "sharing_services" {
  "id" BIGINT [not null]
  "user_id" BIGINT
  "label" TEXT
  "url" TEXT
  "created_at" timestamp(0)
  "updated_at" timestamp(0)

Indexes {
  user_id [name: "sharing_services_user_id_index"]
}
}

Table "starred_entries" {
  "id" BIGINT [not null]
  "user_id" BIGINT
  "feed_id" BIGINT
  "entry_id" BIGINT
  "published" timestamp(0)
  "created_at" timestamp(0)
  "updated_at" timestamp(0)
  "source" TEXT

Indexes {
  user_id [name: "starred_entries_user_id_index"]
  feed_id [name: "starred_entries_feed_id_index"]
  entry_id [name: "starred_entries_entry_id_index"]
  published [name: "starred_entries_published_index"]
}
}

Table "subscriptions" {
  "id" BIGINT [not null]
  "user_id" BIGINT
  "feed_id" BIGINT
  "created_at" timestamp(0)
  "updated_at" timestamp(0)
  "title" TEXT
  "view_inline" BOOLEAN [not null]
  "active" BOOLEAN [not null]
  "push" BOOLEAN [not null]
  "show_updates" BOOLEAN [not null]
  "muted" BOOLEAN [not null]
  "show_retweets" BOOLEAN [not null]
  "media_only" BOOLEAN [not null]
  "kind" BIGINT
  "view_mode" BIGINT

Indexes {
  (feed_id, active, muted, show_updates) [name: "subscriptions_feed_id_active_muted_show_updates_index"]
  (feed_id, active, muted) [name: "subscriptions_feed_id_active_muted_index"]
  user_id [name: "subscriptions_user_id_index"]
  feed_id [name: "subscriptions_feed_id_index"]
  created_at [name: "subscriptions_created_at_index"]
  show_retweets [name: "subscriptions_show_retweets_index"]
  media_only [name: "subscriptions_media_only_index"]
  kind [name: "subscriptions_kind_index"]
}
}

Table "suggested_categories" {
  "id" BIGINT [not null]
  "name" TEXT
  "created_at" timestamp(0)
  "updated_at" timestamp(0)
}

Table "suggested_feeds" {
  "id" BIGINT [not null]
  "suggested_category_id" BIGINT
  "feed_id" BIGINT
  "created_at" timestamp(0)
  "updated_at" timestamp(0) [not null]

Indexes {
  suggested_category_id [name: "suggested_feeds_suggested_category_id_index"]
  feed_id [name: "suggested_feeds_feed_id_index"]
}
}

Table "supported_sharing_services" {
  "id" BIGINT [not null]
  "user_id" BIGINT [not null]
  "service_id" VARCHAR(255) [not null]
  "settings" JSON
  "service_options" JSON
  "created_at" timestamp(0)
  "updated_at" timestamp(0)

Indexes {
  user_id [name: "supported_sharing_services_user_id_index"]
}
}

Table "taggings" {
  "id" BIGINT [not null]
  "feed_id" BIGINT
  "user_id" BIGINT
  "created_at" timestamp(0) [not null]
  "updated_at" timestamp(0) [not null]
  "tag_id" BIGINT

Indexes {
  (user_id, tag_id) [name: "taggings_user_id_tag_id_index"]
  (user_id, feed_id) [name: "taggings_user_id_feed_id_index"]
  user_id [name: "taggings_user_id_index"]
  tag_id [name: "taggings_tag_id_index"]
}
}

Table "tags" {
  "id" BIGINT [not null]
  "name" VARCHAR(255)
  "created_at" timestamp(0) [not null]
  "updated_at" timestamp(0) [not null]

Indexes {
  name [name: "tags_name_index"]
}
}

Table "unreads" {
  "id" BIGINT [not null]
  "user_id" BIGINT [not null]
  "feed_id" BIGINT [not null]
  "entry_id" BIGINT [not null]
  "published" timestamp(0) [not null]
  "entry_created_at" timestamp(0) [not null]
  "created_at" timestamp(0) [not null]
  "updated_at" timestamp(0) [not null]

Indexes {
  (user_id, published) [name: "unreads_user_id_published_index"]
  (user_id, feed_id, published) [name: "unreads_user_id_feed_id_published_index"]
  (user_id, created_at) [name: "unreads_user_id_created_at_index"]
  user_id [name: "unreads_user_id_index"]
  feed_id [name: "unreads_feed_id_index"]
  entry_id [name: "unreads_entry_id_index"]
}
}

Table "updated_entries" {
  "id" BIGINT [not null]
  "user_id" BIGINT
  "entry_id" BIGINT
  "feed_id" BIGINT
  "published" timestamp(0)
  "updated" timestamp(0)
  "created_at" timestamp(0)
  "updated_at" timestamp(0)

Indexes {
  user_id [name: "updated_entries_user_id_index"]
  entry_id [name: "updated_entries_entry_id_index"]
  feed_id [name: "updated_entries_feed_id_index"]
}
}

Table "users" {
  "id" BIGINT [not null]
  "email" VARCHAR(255)
  "password_digest" VARCHAR(255)
  "customer_id" VARCHAR(255)
  "last_4_digits" VARCHAR(255)
  "plan_id" BIGINT
  "admin" BOOLEAN
  "suspended" BOOLEAN
  "created_at" timestamp(0) [not null]
  "updated_at" timestamp(0) [not null]
  "auth_token" VARCHAR(255)
  "password_reset_token" INTEGER [not null]
  "password_reset_sent_at" timestamp(0)
  "settings" JSON
  "starred_token" VARCHAR(255)
  "inbound_email_token" VARCHAR(255)
  "tag_visibility" JSON
  "expires_at" timestamp(0)
  "newsletter_token" VARCHAR(255)
  "price_tier" BIGINT
  "page_token" VARCHAR(255)

Indexes {
  expires_at [name: "users_expires_at_index"]
}
}
