Table "access_tokens" {
  "token" VARCHAR(255) [not null]
  "user_id" INTEGER [not null]
  "last_activity_at" timestamp(0) [not null]
  "lifetime_seconds" INTEGER [not null]
  "created_at" timestamp(0) [not null]

Indexes {
  user_id [name: "access_tokens_user_id_index"]
}
}

Table "api_keys" {
  "key" VARCHAR(255) [not null]
  "id" INTEGER [not null]
  "allowed_ips" VARCHAR(255)
  "scopes" VARCHAR(255)
  "user_id" INTEGER
  "created_at" timestamp(0) [not null]
  "last_activity_at" timestamp(0)

Indexes {
  user_id [name: "api_keys_user_id_index"]
}
}

Table "discussion_tag" {
  "tag_id" INTEGER [not null]
  "discussion_id" INTEGER [not null]

Indexes {
  tag_id [name: "discussion_tag_tag_id_index"]
}
}

Table "discussion_user" {
  "user_id" INTEGER [not null]
  "discussion_id" INTEGER [not null]
  "last_read_at" timestamp(0)
  "last_read_post_number" INTEGER
  "subscription" VARCHAR(255)

Indexes {
  discussion_id [name: "discussion_user_discussion_id_index"]
}
}

Table "discussions" {
  "id" INTEGER [not null]
  "title" VARCHAR(255) [not null]
  "comment_count" INTEGER [not null]
  "participant_count" INTEGER [not null]
  "post_number_index" INTEGER [not null]
  "created_at" timestamp(0) [not null]
  "user_id" INTEGER
  "first_post_id" INTEGER
  "last_posted_at" timestamp(0)
  "last_posted_user_id" INTEGER
  "last_post_id" INTEGER
  "last_post_number" INTEGER
  "hidden_at" timestamp(0)
  "hidden_user_id" INTEGER
  "slug" VARCHAR(255) [not null]
  "is_private" SMALLINT [not null]
  "is_approved" SMALLINT [not null]
  "is_locked" SMALLINT [not null]
  "is_sticky" SMALLINT [not null]

Indexes {
  (created_at, is_sticky) [name: "discussions_created_at_is_sticky_index"]
  comment_count [name: "discussions_comment_count_index"]
  participant_count [name: "discussions_participant_count_index"]
  created_at [name: "discussions_created_at_index"]
  user_id [name: "discussions_user_id_index"]
  first_post_id [name: "discussions_first_post_id_index"]
  last_posted_at [name: "discussions_last_posted_at_index"]
  last_posted_user_id [name: "discussions_last_posted_user_id_index"]
  last_post_id [name: "discussions_last_post_id_index"]
  hidden_at [name: "discussions_hidden_at_index"]
  hidden_user_id [name: "discussions_hidden_user_id_index"]
  is_locked [name: "discussions_is_locked_index"]
}
}

Table "email_tokens" {
  "token" VARCHAR(255) [not null]
  "email" VARCHAR(255) [not null]
  "user_id" INTEGER [not null]
  "created_at" timestamp(0)

Indexes {
  user_id [name: "email_tokens_user_id_index"]
}
}

Table "flags" {
  "id" INTEGER [not null]
  "post_id" INTEGER [not null]
  "type" VARCHAR(255) [not null]
  "user_id" INTEGER
  "reason" VARCHAR(255)
  "reason_detail" TEXT
  "created_at" timestamp(0) [not null]

Indexes {
  post_id [name: "flags_post_id_index"]
  user_id [name: "flags_user_id_index"]
  created_at [name: "flags_created_at_index"]
}
}

Table "group_permission" {
  "group_id" INTEGER [not null]
  "permission" VARCHAR(255) [not null]
}

Table "group_user" {
  "user_id" INTEGER [not null]
  "group_id" INTEGER [not null]

Indexes {
  group_id [name: "group_user_group_id_index"]
}
}

Table "groups" {
  "id" INTEGER [not null]
  "name_singular" VARCHAR(255) [not null]
  "name_plural" VARCHAR(255) [not null]
  "color" VARCHAR(255)
  "icon" VARCHAR(255)
}

Table "login_providers" {
  "id" INTEGER [not null]
  "user_id" INTEGER [not null]
  "provider" VARCHAR(255) [not null]
  "identifier" VARCHAR(255) [not null]
  "created_at" timestamp(0)
  "last_login_at" timestamp(0)

Indexes {
  user_id [name: "login_providers_user_id_index"]
}
}

Table "migrations" {
  "migration" VARCHAR(255) [not null]
  "extension" VARCHAR(255)
}

Table "notifications" {
  "id" INTEGER [not null]
  "user_id" INTEGER [not null]
  "from_user_id" INTEGER
  "type" VARCHAR(255) [not null]
  "subject_id" INTEGER
  "data" BYTE
  "created_at" timestamp(0) [not null]
  "is_deleted" SMALLINT [not null]
  "read_at" timestamp(0)

Indexes {
  user_id [name: "notifications_user_id_index"]
  from_user_id [name: "notifications_from_user_id_index"]
}
}

Table "password_tokens" {
  "token" VARCHAR(255) [not null]
  "user_id" INTEGER [not null]
  "created_at" timestamp(0)

Indexes {
  user_id [name: "password_tokens_user_id_index"]
}
}

Table "post_likes" {
  "post_id" INTEGER [not null]
  "user_id" INTEGER [not null]

Indexes {
  user_id [name: "post_likes_user_id_index"]
}
}

Table "post_mentions_post" {
  "post_id" INTEGER [not null]
  "mentions_post_id" INTEGER [not null]

Indexes {
  mentions_post_id [name: "post_mentions_post_mentions_post_id_index"]
}
}

Table "post_mentions_user" {
  "post_id" INTEGER [not null]
  "mentions_user_id" INTEGER [not null]

Indexes {
  mentions_user_id [name: "post_mentions_user_mentions_user_id_index"]
}
}

Table "post_user" {
  "post_id" INTEGER [not null]
  "user_id" INTEGER [not null]

Indexes {
  user_id [name: "post_user_user_id_index"]
}
}

Table "posts" {
  "id" INTEGER [not null]
  "discussion_id" INTEGER [not null]
  "number" INTEGER
  "created_at" timestamp(0) [not null]
  "user_id" INTEGER
  "type" VARCHAR(255)
  "content" TEXT
  "edited_at" timestamp(0)
  "edited_user_id" INTEGER
  "hidden_at" timestamp(0)
  "hidden_user_id" INTEGER
  "ip_address" VARCHAR(255)
  "is_private" SMALLINT [not null]
  "is_approved" SMALLINT [not null]

Indexes {
  (discussion_id, number) [name: "posts_discussion_id_number_index"]
  (discussion_id, created_at) [name: "posts_discussion_id_created_at_index"]
  (created_at, user_id) [name: "posts_created_at_user_id_index"]
  edited_user_id [name: "posts_edited_user_id_index"]
  hidden_user_id [name: "posts_hidden_user_id_index"]
}
}

Table "registration_tokens" {
  "token" VARCHAR(255) [not null]
  "payload" TEXT
  "created_at" timestamp(0)
  "provider" VARCHAR(255) [not null]
  "identifier" VARCHAR(255) [not null]
  "user_attributes" TEXT
}

Table "settings" {
  "key" VARCHAR(255) [not null]
  "value" TEXT
}

Table "tag_user" {
  "tag_id" INTEGER [not null]
  "user_id" INTEGER [not null]
  "marked_as_read_at" timestamp(0)
  "is_hidden" SMALLINT [not null]

Indexes {
  tag_id [name: "tag_user_tag_id_index"]
}
}

Table "tags" {
  "id" INTEGER [not null]
  "name" VARCHAR(255) [not null]
  "slug" VARCHAR(255) [not null]
  "description" TEXT
  "color" VARCHAR(255)
  "background_path" VARCHAR(255)
  "background_mode" VARCHAR(255)
  "position" INTEGER
  "parent_id" INTEGER
  "default_sort" VARCHAR(255)
  "is_restricted" SMALLINT [not null]
  "is_hidden" SMALLINT [not null]
  "discussion_count" INTEGER [not null]
  "last_posted_at" timestamp(0)
  "last_posted_discussion_id" INTEGER
  "last_posted_user_id" INTEGER
  "icon" VARCHAR(255)

Indexes {
  parent_id [name: "tags_parent_id_index"]
  last_posted_discussion_id [name: "tags_last_posted_discussion_id_index"]
  last_posted_user_id [name: "tags_last_posted_user_id_index"]
}
}

Table "users" {
  "id" INTEGER [not null]
  "username" VARCHAR(255) [not null]
  "email" VARCHAR(255) [not null]
  "is_email_confirmed" SMALLINT [not null]
  "password" VARCHAR(255) [not null]
  "bio" TEXT
  "avatar_url" VARCHAR(255)
  "preferences" BYTE
  "joined_at" timestamp(0)
  "last_seen_at" timestamp(0)
  "marked_all_as_read_at" timestamp(0)
  "read_notifications_at" timestamp(0)
  "discussion_count" INTEGER [not null]
  "comment_count" INTEGER [not null]
  "read_flags_at" timestamp(0)
  "suspended_until" timestamp(0)

Indexes {
  joined_at [name: "users_joined_at_index"]
  last_seen_at [name: "users_last_seen_at_index"]
  discussion_count [name: "users_discussion_count_index"]
  comment_count [name: "users_comment_count_index"]
}
}

Ref:"users"."id" < "access_tokens"."user_id"

Ref:"users"."id" < "api_keys"."user_id"

Ref:"tags"."id" < "discussion_tag"."tag_id"

Ref:"discussions"."id" < "discussion_tag"."discussion_id"

Ref:"users"."id" < "discussion_user"."user_id"

Ref:"discussions"."id" < "discussion_user"."discussion_id"

Ref:"users"."id" < "discussions"."user_id"

Ref:"posts"."id" < "discussions"."first_post_id"

Ref:"users"."id" < "discussions"."last_posted_user_id"

Ref:"posts"."id" < "discussions"."last_post_id"

Ref:"users"."id" < "discussions"."hidden_user_id"

Ref:"users"."id" < "email_tokens"."user_id"

Ref:"posts"."id" < "flags"."post_id"

Ref:"users"."id" < "flags"."user_id"

Ref:"groups"."id" < "group_permission"."group_id"

Ref:"users"."id" < "group_user"."user_id"

Ref:"groups"."id" < "group_user"."group_id"

Ref:"users"."id" < "login_providers"."user_id"

Ref:"users"."id" < "notifications"."user_id"

Ref:"users"."id" < "notifications"."from_user_id"

Ref:"users"."id" < "password_tokens"."user_id"

Ref:"posts"."id" < "post_likes"."post_id"

Ref:"users"."id" < "post_likes"."user_id"

Ref:"posts"."id" < "post_mentions_post"."post_id"

Ref:"posts"."id" < "post_mentions_post"."mentions_post_id"

Ref:"posts"."id" < "post_mentions_user"."post_id"

Ref:"users"."id" < "post_mentions_user"."mentions_user_id"

Ref:"posts"."id" < "post_user"."post_id"

Ref:"users"."id" < "post_user"."user_id"

Ref:"discussions"."id" < "posts"."discussion_id"

Ref:"users"."id" < "posts"."user_id"

Ref:"users"."id" < "posts"."edited_user_id"

Ref:"users"."id" < "posts"."hidden_user_id"

Ref:"tags"."id" < "tag_user"."tag_id"

Ref:"users"."id" < "tag_user"."user_id"

Ref:"tags"."id" < "tags"."parent_id"

Ref:"discussions"."id" < "tags"."last_posted_discussion_id"

Ref:"users"."id" < "tags"."last_posted_user_id"
