Table "attachments" {
  "id" INT [not null]
  "path" NVARCHAR(255) [not null]
  "attachable_id" INT [not null]
  "attachable_type" NVARCHAR(255) [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "comments" {
  "id" INT [not null]
  "ticket_id" INT [not null]
  "user_id" INT
  "new_status" TINYINT [not null]
  "private" TINYINT [not null]
  "body" NVARCHAR(255) [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "failed_jobs" {
  "id" BIGINT [not null]
  "connection" NVARCHAR(255) [not null]
  "queue" NVARCHAR(255) [not null]
  "payload" NVARCHAR(255) [not null]
  "exception" NVARCHAR(255) [not null]
  "failed_at" DATETIME [not null]

Indexes {
  id [pk]
}
}

Table "ideas" {
  "id" INT [not null]
  "requester_id" INT [not null]
  "status" TINYINT [not null]
  "title" NVARCHAR(255) [not null]
  "repository" NVARCHAR(255)
  "issue_id" INT
  "due_date" DATE
  "body" NVARCHAR(255) [not null]
  "development_effort" TINYINT [not null]
  "sales_impact" TINYINT [not null]
  "current_impact" TINYINT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME
  "deleted_at" DATETIME

Indexes {
  id [pk]
}
}

Table "kpis" {
  "date" DATE [not null]
  "type" TINYINT [not null]
  "kpi" TINYINT [not null]
  "relation_id" INT [not null]
  "total" INT [not null]
  "count" INT [not null]

Indexes {
  (date, type, kpi, relation_id) [pk]
}
}

Table "lead_status_updates" {
  "id" INT [not null]
  "new_status" INT [not null]
  "body" NVARCHAR(255)
  "lead_id" INT [not null]
  "user_id" INT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "leads" {
  "id" INT [not null]
  "email" NVARCHAR(255)
  "status" INT [not null]
  "team_id" INT
  "user_id" INT
  "name" NVARCHAR(255) [not null]
  "body" NVARCHAR(255)
  "username" NVARCHAR(255)
  "address" NVARCHAR(255)
  "city" NVARCHAR(255)
  "country" NVARCHAR(255)
  "postal_code" NVARCHAR(255)
  "company" NVARCHAR(255)
  "phone" NVARCHAR(255)
  "created_at" DATETIME
  "updated_at" DATETIME
  "deleted_at" DATETIME

Indexes {
  id [pk]
}
}

Table "memberships" {
  "id" INT [not null]
  "user_id" INT [not null]
  "team_id" INT [not null]
  "admin" TINYINT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "merged_tickets" {
  "id" INT [not null]
  "ticket_id" INT [not null]
  "merged_ticket_id" INT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "migrations" {
  "id" INT [not null]
  "migration" NVARCHAR(255) [not null]
  "batch" INT [not null]

Indexes {
  id [pk]
}
}

Table "password_resets" {
  "email" NVARCHAR(255) [not null]
  "token" NVARCHAR(255) [not null]
  "created_at" DATETIME

Indexes {
  email [name: "password_resets_email_index"]
}
}

Table "requesters" {
  "id" INT [not null]
  "name" NVARCHAR(255) [not null]
  "email" NVARCHAR(255)
  "created_at" DATETIME
  "updated_at" DATETIME
  "no_reply" TINYINT [not null]

Indexes {
  id [pk]
  email [unique, name: "requesters_email_unique"]
}
}

Table "settings" {
  "id" INT [not null]
  "slack_webhook_url" NVARCHAR(255)
  "default_team_id" INT
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "taggables" {
  "tag_id" INT [not null]
  "taggable_id" INT [not null]
  "taggable_type" NVARCHAR(255) [not null]
}

Table "tags" {
  "id" INT [not null]
  "name" NVARCHAR(255) [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "tasks" {
  "id" INT [not null]
  "lead_id" INT [not null]
  "user_id" INT [not null]
  "body" NVARCHAR(255) [not null]
  "datetime" DATETIME
  "completed" TINYINT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "teams" {
  "id" INT [not null]
  "name" NVARCHAR(255) [not null]
  "email" NVARCHAR(255)
  "slack_webhook_url" NVARCHAR(255)
  "token" NVARCHAR(255) [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "ticket_events" {
  "id" INT [not null]
  "ticket_id" INT [not null]
  "user_id" INT
  "body" NVARCHAR(255) [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "ticket_types" {
  "id" INT [not null]
  "name" NVARCHAR(255) [not null]
  "color" NVARCHAR(255) [not null]
  "deleted_at" DATETIME
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "tickets" {
  "id" INT [not null]
  "title" NVARCHAR(255) [not null]
  "body" NVARCHAR(255) [not null]
  "public_token" NVARCHAR(255) [not null]
  "requester_id" INT [not null]
  "team_id" INT
  "user_id" INT
  "status" TINYINT [not null]
  "priority" TINYINT [not null]
  "level" TINYINT [not null]
  "rating" TINYINT
  "created_at" DATETIME
  "updated_at" DATETIME
  "deleted_at" DATETIME
  "ticket_type_id" INT
  "subject" NVARCHAR(255)
  "summary" NVARCHAR(255)

Indexes {
  id [pk]
  public_token [unique, name: "tickets_public_token_unique"]
}
}

Table "user_settings" {
  "id" INT [not null]
  "user_id" INT [not null]
  "daily_tasks_notification" TINYINT [not null]
  "tickets_signature" NVARCHAR(255)
  "new_ticket_notification" TINYINT [not null]
  "ticket_assigned_notification" TINYINT [not null]
  "ticket_updated_notification" TINYINT [not null]
  "new_lead_notification" TINYINT [not null]
  "lead_assigned_notification" TINYINT [not null]
  "new_idea_notification" TINYINT [not null]
  "mention_notification" TINYINT [not null]
  "ticket_rated_notification" TINYINT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME
  "escalated_ticket_notification" TINYINT [not null]

Indexes {
  id [pk]
}
}

Table "users" {
  "id" INT [not null]
  "name" NVARCHAR(255) [not null]
  "email" NVARCHAR(255) [not null]
  "locale" NVARCHAR(255) [not null]
  "password" NVARCHAR(255) [not null]
  "admin" TINYINT [not null]
  "assistant" TINYINT [not null]
  "remember_token" NVARCHAR(255)
  "created_at" DATETIME
  "updated_at" DATETIME
  "can_see_reports" TINYINT [not null]
  "token" NVARCHAR(255)

Indexes {
  id [pk]
  email [unique, name: "users_email_unique"]
  token [unique, name: "users_token_unique"]
}
}

Ref "lead_status_updates_lead_id_foreign":"leads"."id" < "lead_status_updates"."lead_id"

Ref "tasks_lead_id_foreign":"leads"."id" < "tasks"."lead_id"

Ref "taggables_taggable_id_foreign":"leads"."id" < "taggables"."taggable_id"

Ref "merged_tickets_merged_ticket_id_foreign":"merged_tickets"."id" < "merged_tickets"."merged_ticket_id"

Ref "ideas_requester_id_foreign":"requesters"."id" < "ideas"."requester_id"

Ref "tickets_requester_id_foreign":"requesters"."id" < "tickets"."requester_id"

Ref "taggables_taggable_id_foreign":"tickets"."id" < "taggables"."taggable_id"

Ref "taggables_tag_id_foreign":"tags"."id" < "taggables"."tag_id"

Ref "leads_team_id_foreign":"teams"."id" < "leads"."team_id"

Ref "memberships_team_id_foreign":"teams"."id" < "memberships"."team_id"

Ref "tickets_team_id_foreign":"teams"."id" < "tickets"."team_id"

Ref "tickets_ticket_type_id_foreign":"ticket_types"."id" < "tickets"."ticket_type_id"

Ref "comments_ticket_id_foreign":"tickets"."id" < "comments"."ticket_id"

Ref "merged_tickets_ticket_id_foreign":"tickets"."id" < "merged_tickets"."ticket_id"

Ref "ticket_events_ticket_id_foreign":"tickets"."id" < "ticket_events"."ticket_id"

Ref "comments_user_id_foreign":"users"."id" < "comments"."user_id"

Ref "lead_status_updates_user_id_foreign":"users"."id" < "lead_status_updates"."user_id"

Ref "leads_user_id_foreign":"users"."id" < "leads"."user_id"

Ref "memberships_user_id_foreign":"users"."id" < "memberships"."user_id"

Ref "tasks_user_id_foreign":"users"."id" < "tasks"."user_id"

Ref "ticket_events_user_id_foreign":"users"."id" < "ticket_events"."user_id"

Ref "tickets_user_id_foreign":"users"."id" < "tickets"."user_id"

Ref "user_settings_user_id_foreign":"users"."id" < "user_settings"."user_id"
