Table "accounts_profile" {
  "id" INT [not null]
  "next_report_date" DATETIME
  "reports_allowed" TINYINT [not null]
  "user_id" INT
  "ping_log_limit" INT [not null]
  "token" NVARCHAR(255) [not null]
  "check_limit" INT [not null]
  "last_sms_date" DATETIME
  "sms_limit" INT [not null]
  "sms_sent" INT [not null]
  "team_limit" INT [not null]
  "sort" NVARCHAR(255) [not null]
  "nag_period" BIGINT [not null]
  "next_nag_date" DATETIME
  "deletion_notice_date" DATETIME
  "last_active_date" DATETIME

Indexes {
  id [pk]
  user_id [unique, name: "accounts_profile_user_id_unique"]
}
}

Table "accounts_project" {
  "id" INT [not null]
  "code" NCHAR(255) [not null]
  "name" NVARCHAR(255) [not null]
  "api_key" NVARCHAR(255) [not null]
  "api_key_readonly" NVARCHAR(255) [not null]
  "owner_id" INT [not null]
  "badge_key" NVARCHAR(255) [not null]

Indexes {
  id [pk]
  code [unique, name: "accounts_project_code_unique"]
  api_key [name: "accounts_project_api_key_index"]
  api_key_readonly [name: "accounts_project_api_key_readonly_index"]
  owner_id [name: "accounts_project_owner_id_index"]
  badge_key [unique, name: "accounts_project_badge_key_unique"]
}
}

Table "accounts_member" {
  "id" INT [not null]
  "user_id" INT [not null]
  "project_id" INT [not null]

Indexes {
  id [pk]
  user_id [name: "accounts_member_user_id_index"]
  project_id [name: "accounts_member_project_id_index"]
}
}

Table "api_channel" {
  "id" INT [not null]
  "code" NCHAR(255) [not null]
  "created" DATETIME [not null]
  "kind" NVARCHAR(255) [not null]
  "value" NVARCHAR(255) [not null]
  "email_verified" TINYINT [not null]
  "name" NVARCHAR(255) [not null]
  "project_id" INT [not null]
  "last_error" NVARCHAR(255) [not null]

Indexes {
  id [pk]
  code [unique, name: "api_channel_code_unique"]
  project_id [name: "api_channel_project_id_index"]
}
}

Table "api_channel_checks" {
  "id" INT [not null]
  "channel_id" INT [not null]
  "check_id" INT [not null]

Indexes {
  (channel_id, check_id) [unique, name: "api_channel_checks_channel_id_check_id_unique"]
  id [pk]
  check_id [name: "api_channel_checks_check_id_index"]
}
}

Table "api_check" {
  "id" INT [not null]
  "code" NCHAR(255) [not null]
  "last_ping" DATETIME
  "alert_after" DATETIME
  "status" NVARCHAR(255) [not null]
  "timeout" BIGINT [not null]
  "name" NVARCHAR(255) [not null]
  "created" DATETIME [not null]
  "grace" BIGINT [not null]
  "tags" NVARCHAR(255) [not null]
  "n_pings" INT [not null]
  "kind" NVARCHAR(255) [not null]
  "schedule" NVARCHAR(255) [not null]
  "tz" NVARCHAR(255) [not null]
  "has_confirmation_link" TINYINT [not null]
  "last_ping_was_fail" TINYINT
  "desc" NVARCHAR(255) [not null]
  "last_start" DATETIME
  "subject" NVARCHAR(255) [not null]
  "project_id" INT [not null]
  "last_duration" BIGINT
  "methods" NVARCHAR(255) [not null]

Indexes {
  id [pk]
  code [unique, name: "api_check_code_unique"]
  alert_after [name: "api_check_alert_after_index"]
  project_id [name: "api_check_project_id_index"]
}
}

Table "api_flip" {
  "id" INT [not null]
  "created" DATETIME [not null]
  "processed" DATETIME
  "old_status" NVARCHAR(255) [not null]
  "new_status" NVARCHAR(255) [not null]
  "owner_id" INT [not null]

Indexes {
  id [pk]
  processed [name: "api_flip_processed_index"]
  owner_id [name: "api_flip_owner_id_index"]
}
}

Table "api_notification" {
  "id" INT [not null]
  "check_status" NVARCHAR(255) [not null]
  "created" DATETIME [not null]
  "channel_id" INT [not null]
  "owner_id" INT [not null]
  "error" NVARCHAR(255) [not null]
  "code" NCHAR(255)

Indexes {
  id [pk]
  channel_id [name: "api_notification_channel_id_index"]
  owner_id [name: "api_notification_owner_id_index"]
}
}

Table "api_ping" {
  "id" BIGINT [not null]
  "created" DATETIME [not null]
  "remote_addr" NCHAR(255)
  "method" NVARCHAR(255) [not null]
  "ua" NVARCHAR(255) [not null]
  "owner_id" INT [not null]
  "scheme" NVARCHAR(255) [not null]
  "n" INT
  "body" NVARCHAR(255)
  "kind" NVARCHAR(255)

Indexes {
  id [pk]
  owner_id [name: "api_ping_owner_id_index"]
}
}

Table "api_tokenbucket" {
  "id" INT [not null]
  "value" NVARCHAR(255) [not null]
  "tokens" FLOAT [not null]
  "updated" DATETIME [not null]

Indexes {
  id [pk]
  value [unique, name: "api_tokenbucket_value_unique"]
}
}

Table "auth_user" {
  "id" INT [not null]
  "password" NVARCHAR(255) [not null]
  "last_login" DATETIME
  "is_superuser" TINYINT [not null]
  "username" NVARCHAR(255) [not null]
  "first_name" NVARCHAR(255) [not null]
  "last_name" NVARCHAR(255) [not null]
  "email" NVARCHAR(255) [not null]
  "is_staff" TINYINT [not null]
  "is_active" TINYINT [not null]
  "date_joined" DATETIME [not null]

Indexes {
  id [pk]
  username [unique, name: "auth_user_username_unique"]
}
}

Table "payments_subscription" {
  "id" INT [not null]
  "customer_id" NVARCHAR(255) [not null]
  "payment_method_token" NVARCHAR(255) [not null]
  "subscription_id" NVARCHAR(255) [not null]
  "user_id" INT
  "plan_id" NVARCHAR(255) [not null]
  "address_id" NVARCHAR(255) [not null]
  "send_invoices" TINYINT [not null]
  "plan_name" NVARCHAR(255) [not null]
  "invoice_email" NVARCHAR(255) [not null]

Indexes {
  id [pk]
  user_id [unique, name: "payments_subscription_user_id_unique"]
}
}

Ref "accounts_profile_user_id_foreign":"auth_user"."id" < "accounts_profile"."user_id"

Ref "accounts_project_owner_id_foreign":"auth_user"."id" < "accounts_project"."owner_id"

Ref "accounts_member_user_id_foreign":"auth_user"."id" < "accounts_member"."user_id"

Ref "accounts_member_project_id_foreign":"accounts_project"."id" < "accounts_member"."project_id"

Ref "api_channel_project_id_foreign":"accounts_project"."id" < "api_channel"."project_id"

Ref "api_channel_checks_channel_id_foreign":"api_channel"."id" < "api_channel_checks"."channel_id"

Ref "api_channel_checks_check_id_foreign":"api_check"."id" < "api_channel_checks"."check_id"

Ref "api_check_project_id_foreign":"accounts_project"."id" < "api_check"."project_id"

Ref "api_flip_owner_id_foreign":"api_check"."id" < "api_flip"."owner_id"

Ref "api_notification_channel_id_foreign":"api_channel"."id" < "api_notification"."channel_id"

Ref "api_notification_owner_id_foreign":"api_check"."id" < "api_notification"."owner_id"

Ref "api_ping_owner_id_foreign":"api_check"."id" < "api_ping"."owner_id"

Ref "payments_subscription_user_id_foreign":"auth_user"."id" < "payments_subscription"."user_id"
