Table "users" {
  "id" INT [pk, not null, increment]
  "name" VARCHAR(255) [not null]
  "email" VARCHAR(255) [not null]
  "password" VARCHAR(255) [not null]
  "is_admin" TINYINT(1) [not null]
  "preferences" TEXT
  "remember_token" VARCHAR(255)
  "created_at" DATETIME [not null]
  "updated_at" DATETIME [not null]
}

Table "password_resets" {
  "email" VARCHAR(255) [not null]
  "token" VARCHAR(255) [not null]
  "created_at" DATETIME [not null]
}

Table "artists" {
  "id" INT [pk, not null, increment]
  "name" VARCHAR(255) [not null]
  "image" VARCHAR(255)
  "created_at" DATETIME [not null]
  "updated_at" DATETIME [not null]
}

Table "albums" {
  "id" INT [pk, not null, increment]
  "artist_id" INT [not null]
  "name" VARCHAR(255) [not null]
  "cover" VARCHAR(255) [not null]
  "created_at" DATETIME [not null]
  "updated_at" DATETIME [not null]
}

Table "songs" {
  "id" VARCHAR(255) [not null]
  "album_id" INT [not null]
  "artist_id" INT
  "title" VARCHAR(255) [not null]
  "length" DOUBLE(8,2) [not null]
  "track" INT
  "disc" INT [not null]
  "lyrics" TEXT [not null]
  "path" TEXT [not null]
  "mtime" INT [not null]
  "created_at" DATETIME [not null]
  "updated_at" DATETIME [not null]
}

Table "playlists" {
  "id" INT [pk, not null, increment]
  "user_id" INT [not null]
  "name" VARCHAR(255) [not null]
  "rules" TEXT
  "created_at" DATETIME [not null]
  "updated_at" DATETIME [not null]
}

Table "interactions" {
  "id" BIGINT [pk, not null, increment]
  "user_id" INT [not null]
  "song_id" VARCHAR(255) [not null]
  "liked" TINYINT(1) [not null]
  "play_count" INT [not null]
  "created_at" DATETIME [not null]
  "updated_at" DATETIME [not null]
}

Table "playlist_song" {
  "id" INT [pk, not null, increment]
  "playlist_id" INT [not null]
  "song_id" VARCHAR(255) [not null]
}

Table "settings" {
  "key" VARCHAR(255) [not null]
  "value" TEXT [not null]
}

Ref:"users"."id" < "playlists"."user_id"

Ref:"users"."id" < "interactions"."user_id"

Ref:"artists"."id" < "albums"."artist_id"

Ref:"albums"."id" < "songs"."album_id"

Ref:"songs"."id" < "interactions"."song_id"

Ref:"songs"."id" < "playlist_song"."song_id"

Ref:"artists"."id" < "songs"."artist_id"

Ref:"playlists"."id" < "playlist_song"."playlist_id"
