Table "ticketit_statuses" {
  "id" INT [pk, not null, increment]
  "name" VARCHAR(255) [not null]
  "color" BIGINT [not null]
}

Table "ticketit_priorities" {
  "id" INT [pk, not null, increment]
  "name" VARCHAR(255) [not null]
  "color" BIGINT [not null]
}

Table "ticketit_categories" {
  "id" INT [pk, not null, increment]
  "name" VARCHAR(255) [not null]
  "color" BIGINT [not null]
}

Table "ticketit_categories_users" {
  "category_id" INT [pk, not null, increment]
  "user_id" INT [not null]
}

Table "ticketit" {
  "id" INT [pk, not null, increment]
  "subject" VARCHAR(255) [not null]
  "content" LONGTEXT [not null]
  "html" LONGTEXT
  "status_id" INT [not null]
  "priority_id" INT [not null]
  "user_id" INT [not null]
  "agent_id" INT [not null]
  "category_id" INT [not null]
  "created_at" DATETIME [not null]
  "updated_at" BIGINT [not null]
  "completed_at" TIMESTAMP
}

Table "ticketit_comments" {
  "id" INT [pk, not null, increment]
  "content" TEXT [not null]
  "user_id" INT [not null]
  "ticket_id" INT [not null]
  "created_at" BIGINT [not null]
  "updated_at" DATETIME [not null]
  "content2" LONGTEXT [not null]
  "html" LONGTEXT
}

Table "ticketit_audits" {
  "id" INT [pk, not null, increment]
  "operation" TEXT [not null]
  "user_id" INT [not null]
  "ticket_id" INT [not null]
  "created_at" DATETIME [not null]
  "updated_at" DATETIME [not null]
}

Table "users" {
  "id" INT [pk, not null, increment]
  "ticketit_admin" TINYINT(1) [not null]
  "ticketit_agent" TINYINT(1) [not null]
}

Table "ticketit_settings" {
  "id" INT [pk, not null, increment]
  "lang" VARCHAR(255)
  "slug" VARCHAR(255) [not null]
  "value" MEDIUMTEXT [not null]
  "default" MEDIUMTEXT [not null]
  "created_at" DATETIME [not null]
  "updated_at" DATETIME [not null]
}

Ref:"ticketit_priorities"."id" < "ticketit"."priority_id"

Ref:"ticketit_statuses"."id" < "ticketit"."status_id"

Ref:"users"."id" < "ticketit"."agent_id"

Ref:"ticketit_categories"."id" < "ticketit"."category_id"

Ref:"ticketit"."id" < "ticketit_comments"."ticket_id"

Ref:"ticketit"."id" < "ticketit_audits"."ticket_id"

Ref:"users"."id" < "ticketit"."user_id"

Ref:"users"."id" < "ticketit_categories_users"."user_id"

Ref:"users"."id" < "ticketit_comments"."user_id"

Ref:"users"."id" < "ticketit_audits"."user_id"
