Table "account_sectors" {
  "id" INT [not null]
  "name" NVARCHAR(255) [not null]
  "type" NVARCHAR(255) [not null]
  "school_id" INT [not null]
  "user_id" INT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "accounts" {
  "id" INT [not null]
  "name" NVARCHAR(255) [not null]
  "type" NVARCHAR(255) [not null]
  "amount" INT [not null]
  "description" NVARCHAR(255) [not null]
  "school_id" INT [not null]
  "user_id" INT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "attendances" {
  "id" INT [not null]
  "student_id" INT [not null]
  "section_id" INT [not null]
  "exam_id" INT [not null]
  "present" SMALLINT [not null]
  "user_id" INT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "books" {
  "id" INT [not null]
  "book_code" NVARCHAR(255) [not null]
  "title" NVARCHAR(255) [not null]
  "author" NVARCHAR(255) [not null]
  "quantity" INT [not null]
  "rackNo" NVARCHAR(255) [not null]
  "rowNo" NVARCHAR(255) [not null]
  "img_path" NVARCHAR(255) [not null]
  "about" NVARCHAR(255) [not null]
  "type" NVARCHAR(255) [not null]
  "price" INT [not null]
  "class_id" INT [not null]
  "school_id" INT [not null]
  "user_id" INT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
  book_code [unique, name: "books_book_code_unique"]
}
}

Table "classes" {
  "id" INT [not null]
  "class_number" NVARCHAR(255) [not null]
  "school_id" INT [not null]
  "group" NVARCHAR(255) [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "courses" {
  "id" INT [not null]
  "course_name" NVARCHAR(255) [not null]
  "class_id" INT [not null]
  "course_type" NVARCHAR(255) [not null]
  "course_time" NVARCHAR(255) [not null]
  "grade_system_name" NVARCHAR(255) [not null]
  "quiz_count" INT [not null]
  "assignment_count" INT [not null]
  "ct_count" INT [not null]
  "quiz_percent" INT [not null]
  "attendance_percent" INT [not null]
  "assignment_percent" INT [not null]
  "ct_percent" INT [not null]
  "final_exam_percent" INT [not null]
  "practical_percent" INT [not null]
  "att_fullmark" INT [not null]
  "quiz_fullmark" INT [not null]
  "a_fullmark" INT [not null]
  "ct_fullmark" INT [not null]
  "final_fullmark" INT [not null]
  "practical_fullmark" INT [not null]
  "school_id" INT [not null]
  "exam_id" INT [not null]
  "teacher_id" INT [not null]
  "section_id" INT [not null]
  "user_id" INT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "departments" {
  "id" INT [not null]
  "school_id" INT [not null]
  "department_name" NVARCHAR(255) [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "events" {
  "id" INT [not null]
  "file_path" NVARCHAR(255) [not null]
  "title" NVARCHAR(255) [not null]
  "description" NVARCHAR(255) [not null]
  "active" SMALLINT [not null]
  "school_id" INT [not null]
  "user_id" INT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "exam_for_classes" {
  "id" INT [not null]
  "class_id" INT [not null]
  "exam_id" INT [not null]
  "active" SMALLINT [not null]

Indexes {
  id [pk]
}
}

Table "exams" {
  "id" INT [not null]
  "exam_name" NVARCHAR(255) [not null]
  "active" SMALLINT [not null]
  "notice_published" SMALLINT [not null]
  "result_published" SMALLINT [not null]
  "school_id" INT [not null]
  "user_id" INT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME
  "term" NVARCHAR(255) [not null]
  "start_date" NVARCHAR(255) [not null]
  "end_date" NVARCHAR(255) [not null]

Indexes {
  id [pk]
}
}

Table "faqs" {
  "id" INT [not null]
  "question" NVARCHAR(255) [not null]
  "answer" NVARCHAR(255) [not null]
  "user_id" INT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "feedbacks" {
  "id" INT [not null]
  "description" NVARCHAR(255) [not null]
  "teacher_id" INT [not null]
  "student_id" INT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "fees" {
  "id" INT [not null]
  "fee_name" NVARCHAR(255) [not null]
  "school_id" INT [not null]
  "user_id" INT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "forms" {
  "id" INT [not null]
  "name" NVARCHAR(255) [not null]
  "file_path" NVARCHAR(255) [not null]
  "school_id" INT [not null]
  "user_id" INT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "grade_systems" {
  "id" INT [not null]
  "grade_system_name" NVARCHAR(255) [not null]
  "grade" NVARCHAR(255) [not null]
  "point" FLOAT [not null]
  "from_mark" INT [not null]
  "to_mark" INT [not null]
  "school_id" INT [not null]
  "user_id" INT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "grades" {
  "id" INT [not null]
  "marks" FLOAT [not null]
  "gpa" FLOAT [not null]
  "attendance" FLOAT [not null]
  "quiz1" FLOAT [not null]
  "quiz2" FLOAT [not null]
  "quiz3" FLOAT [not null]
  "quiz4" FLOAT [not null]
  "quiz5" FLOAT [not null]
  "ct1" FLOAT [not null]
  "ct2" FLOAT [not null]
  "ct3" FLOAT [not null]
  "ct4" FLOAT [not null]
  "ct5" FLOAT [not null]
  "assignment1" FLOAT [not null]
  "assignment2" FLOAT [not null]
  "assignment3" FLOAT [not null]
  "written" FLOAT [not null]
  "mcq" FLOAT [not null]
  "practical" FLOAT [not null]
  "exam_id" INT [not null]
  "student_id" INT [not null]
  "teacher_id" INT [not null]
  "course_id" INT [not null]
  "user_id" INT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "homeworks" {
  "id" INT [not null]
  "file_path" NVARCHAR(255) [not null]
  "description" NVARCHAR(255) [not null]
  "teacher_id" INT [not null]
  "section_id" INT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "issued_books" {
  "id" INT [not null]
  "student_code" INT [not null]
  "book_id" INT [not null]
  "quantity" INT [not null]
  "school_id" INT [not null]
  "issue_date" DATE [not null]
  "return_date" DATE [not null]
  "fine" DECIMAL(8,2) [not null]
  "borrowed" SMALLINT [not null]
  "user_id" INT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "messages" {
  "id" INT [not null]
  "phone_number" NVARCHAR(255) [not null]
  "email" NVARCHAR(255) [not null]
  "message" NVARCHAR(255) [not null]
  "school_id" INT [not null]
  "user_id" INT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
  email [unique, name: "messages_email_unique"]
}
}

Table "migrations" {
  "id" INT [not null]
  "migration" NVARCHAR(255) [not null]
  "batch" INT [not null]

Indexes {
  id [pk]
}
}

Table "notices" {
  "id" INT [not null]
  "file_path" NVARCHAR(255) [not null]
  "title" NVARCHAR(255) [not null]
  "description" NVARCHAR(255) [not null]
  "active" SMALLINT [not null]
  "school_id" INT [not null]
  "user_id" INT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "notifications" {
  "id" INT [not null]
  "sent_status" SMALLINT [not null]
  "active" SMALLINT [not null]
  "message" NVARCHAR(255) [not null]
  "student_id" INT [not null]
  "user_id" INT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "oauth_access_tokens" {
  "id" NVARCHAR(255) [not null]
  "user_id" INT
  "client_id" INT [not null]
  "name" NVARCHAR(255)
  "scopes" NVARCHAR(255)
  "revoked" SMALLINT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME
  "expires_at" DATETIME

Indexes {
  id [pk]
  user_id [name: "oauth_access_tokens_user_id_index"]
}
}

Table "oauth_auth_codes" {
  "id" NVARCHAR(255) [not null]
  "user_id" INT [not null]
  "client_id" INT [not null]
  "scopes" NVARCHAR(255)
  "revoked" SMALLINT [not null]
  "expires_at" DATETIME

Indexes {
  id [pk]
}
}

Table "oauth_clients" {
  "id" INT [not null]
  "user_id" INT
  "name" NVARCHAR(255) [not null]
  "secret" NVARCHAR(255) [not null]
  "redirect" NVARCHAR(255) [not null]
  "personal_access_client" SMALLINT [not null]
  "password_client" SMALLINT [not null]
  "revoked" SMALLINT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
  user_id [name: "oauth_clients_user_id_index"]
}
}

Table "oauth_personal_access_clients" {
  "id" INT [not null]
  "client_id" INT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
  client_id [name: "oauth_personal_access_clients_client_id_index"]
}
}

Table "oauth_refresh_tokens" {
  "id" NVARCHAR(255) [not null]
  "access_token_id" NVARCHAR(255) [not null]
  "revoked" SMALLINT [not null]
  "expires_at" DATETIME

Indexes {
  id [pk]
  access_token_id [name: "oauth_refresh_tokens_access_token_id_index"]
}
}

Table "password_resets" {
  "email" NVARCHAR(255) [not null]
  "token" NVARCHAR(255) [not null]
  "created_at" DATETIME

Indexes {
  email [name: "password_resets_email_index"]
}
}

Table "payments" {
  "id" INT [not null]
  "payment_id" NVARCHAR(255) [not null]
  "payment_status" SMALLINT [not null]
  "amount" FLOAT [not null]
  "custormer_id" INT [not null]
  "charge_for" NVARCHAR(255) [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "routines" {
  "id" INT [not null]
  "file_path" NVARCHAR(255) [not null]
  "title" NVARCHAR(255) [not null]
  "description" NVARCHAR(255) [not null]
  "active" SMALLINT [not null]
  "school_id" INT [not null]
  "user_id" INT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME
  "section_id" INT [not null]

Indexes {
  id [pk]
}
}

Table "schools" {
  "id" INT [not null]
  "name" NVARCHAR(255) [not null]
  "established" NVARCHAR(255) [not null]
  "about" NVARCHAR(255) [not null]
  "medium" NVARCHAR(255) [not null]
  "code" INT [not null]
  "theme" NVARCHAR(255) [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
  code [unique, name: "schools_code_unique"]
}
}

Table "sections" {
  "id" INT [not null]
  "section_number" NVARCHAR(255) [not null]
  "room_number" INT [not null]
  "class_id" INT [not null]
  "user_id" INT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "student_board_exams" {
  "id" INT [not null]
  "student_id" INT [not null]
  "exam_name" NVARCHAR(255) [not null]
  "group" NVARCHAR(255) [not null]
  "roll" INT [not null]
  "registration" INT [not null]
  "session" NVARCHAR(255) [not null]
  "board" NVARCHAR(255) [not null]
  "passing_year" INT [not null]
  "institution_name" NVARCHAR(255) [not null]
  "gpa" FLOAT [not null]
  "user_id" INT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "student_infos" {
  "id" INT [not null]
  "student_id" INT [not null]
  "session" NVARCHAR(255) [not null]
  "version" NVARCHAR(255) [not null]
  "group" NVARCHAR(255) [not null]
  "birthday" DATETIME [not null]
  "religion" NVARCHAR(255) [not null]
  "father_name" NVARCHAR(255) [not null]
  "father_phone_number" NVARCHAR(255) [not null]
  "father_national_id" NVARCHAR(255) [not null]
  "father_occupation" NVARCHAR(255) [not null]
  "father_designation" NVARCHAR(255) [not null]
  "father_annual_income" INT [not null]
  "mother_name" NVARCHAR(255) [not null]
  "mother_phone_number" NVARCHAR(255) [not null]
  "mother_national_id" NVARCHAR(255) [not null]
  "mother_occupation" NVARCHAR(255) [not null]
  "mother_designation" NVARCHAR(255) [not null]
  "mother_annual_income" INT [not null]
  "user_id" INT
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "subscriptions" {
  "id" INT [not null]
  "user_id" INT [not null]
  "name" NVARCHAR(255) [not null]
  "stripe_id" NVARCHAR(255) [not null]
  "stripe_plan" NVARCHAR(255) [not null]
  "quantity" INT [not null]
  "trial_ends_at" DATETIME
  "ends_at" DATETIME
  "created_at" DATETIME
  "updated_at" DATETIME

Indexes {
  id [pk]
}
}

Table "syllabuses" {
  "id" INT [not null]
  "file_path" NVARCHAR(255) [not null]
  "title" NVARCHAR(255) [not null]
  "description" NVARCHAR(255) [not null]
  "active" SMALLINT [not null]
  "school_id" INT [not null]
  "user_id" INT [not null]
  "created_at" DATETIME
  "updated_at" DATETIME
  "class_id" INT [not null]

Indexes {
  id [pk]
}
}

Table "users" {
  "id" INT [not null]
  "name" NVARCHAR(255) [not null]
  "email" NVARCHAR(255) [not null]
  "password" NVARCHAR(255) [not null]
  "role" NVARCHAR(255) [not null]
  "active" SMALLINT [not null]
  "school_id" INT
  "code" INT
  "student_code" INT
  "gender" NVARCHAR(255) [not null]
  "blood_group" NVARCHAR(255) [not null]
  "nationality" NVARCHAR(255) [not null]
  "phone_number" NVARCHAR(255) [not null]
  "address" NVARCHAR(255) [not null]
  "about" NVARCHAR(255) [not null]
  "pic_path" NVARCHAR(255) [not null]
  "verified" SMALLINT [not null]
  "section_id" INT
  "remember_token" NVARCHAR(255)
  "created_at" DATETIME
  "updated_at" DATETIME
  "department_id" INT [not null]
  "stripe_id" NVARCHAR(255)
  "card_brand" NVARCHAR(255)
  "card_last_four" NVARCHAR(255)
  "trial_ends_at" DATETIME

Indexes {
  id [pk]
  email [unique, name: "users_email_unique"]
  student_code [unique, name: "users_student_code_unique"]
  phone_number [unique, name: "users_phone_number_unique"]
}
}

Ref "issued_books_book_id_foreign":"books"."id" < "issued_books"."book_id"

Ref "books_class_id_foreign":"classes"."id" < "books"."class_id"

Ref "courses_class_id_foreign":"classes"."id" < "courses"."class_id"

Ref "exam_for_classes_class_id_foreign":"classes"."id" < "exam_for_classes"."class_id"

Ref "sections_class_id_foreign":"classes"."id" < "sections"."class_id"

Ref "syllabuses_class_id_foreign":"classes"."id" < "syllabuses"."class_id"

Ref "grades_course_id_foreign":"courses"."id" < "grades"."course_id"

Ref "users_department_id_foreign":"departments"."id" < "users"."department_id"

Ref "attendances_exam_id_foreign":"exams"."id" < "attendances"."exam_id"

Ref "courses_exam_id_foreign":"exams"."id" < "courses"."exam_id"

Ref "exam_for_classes_exam_id_foreign":"exams"."id" < "exam_for_classes"."exam_id"

Ref "grades_exam_id_foreign":"exams"."id" < "grades"."exam_id"

Ref "feedbacks_teacher_id_foreign":"users"."id" < "feedbacks"."teacher_id"

Ref "feedbacks_student_id_foreign":"users"."id" < "feedbacks"."student_id"

Ref "payments_payment_id_foreign":"payments"."id" < "payments"."payment_id"

Ref "payments_custormer_id_foreign":"users"."id" < "payments"."custormer_id"

Ref "account_sectors_school_id_foreign":"schools"."id" < "account_sectors"."school_id"

Ref "accounts_school_id_foreign":"schools"."id" < "accounts"."school_id"

Ref "books_school_id_foreign":"schools"."id" < "books"."school_id"

Ref "classes_school_id_foreign":"schools"."id" < "classes"."school_id"

Ref "courses_school_id_foreign":"schools"."id" < "courses"."school_id"

Ref "departments_school_id_foreign":"schools"."id" < "departments"."school_id"

Ref "events_school_id_foreign":"schools"."id" < "events"."school_id"

Ref "exams_school_id_foreign":"schools"."id" < "exams"."school_id"

Ref "fees_school_id_foreign":"schools"."id" < "fees"."school_id"

Ref "forms_school_id_foreign":"schools"."id" < "forms"."school_id"

Ref "grade_systems_school_id_foreign":"schools"."id" < "grade_systems"."school_id"

Ref "issued_books_school_id_foreign":"schools"."id" < "issued_books"."school_id"

Ref "messages_school_id_foreign":"schools"."id" < "messages"."school_id"

Ref "notices_school_id_foreign":"schools"."id" < "notices"."school_id"

Ref "routines_school_id_foreign":"schools"."id" < "routines"."school_id"

Ref "syllabuses_school_id_foreign":"schools"."id" < "syllabuses"."school_id"

Ref "users_school_id_foreign":"schools"."id" < "users"."school_id"

Ref "attendances_section_id_foreign":"sections"."id" < "attendances"."section_id"

Ref "courses_section_id_foreign":"sections"."id" < "courses"."section_id"

Ref "homeworks_section_id_foreign":"sections"."id" < "homeworks"."section_id"

Ref "routines_section_id_foreign":"sections"."id" < "routines"."section_id"

Ref "users_section_id_foreign":"sections"."id" < "users"."section_id"

Ref "student_board_exams_student_id_foreign":"users"."id" < "student_board_exams"."student_id"

Ref "student_infos_student_id_foreign":"users"."id" < "student_infos"."student_id"

Ref "account_sectors_user_id_foreign":"users"."id" < "account_sectors"."user_id"

Ref "accounts_user_id_foreign":"users"."id" < "accounts"."user_id"

Ref "attendances_user_id_foreign":"users"."id" < "attendances"."user_id"

Ref "books_user_id_foreign":"users"."id" < "books"."user_id"

Ref "courses_user_id_foreign":"users"."id" < "courses"."user_id"

Ref "events_user_id_foreign":"users"."id" < "events"."user_id"

Ref "exams_user_id_foreign":"users"."id" < "exams"."user_id"

Ref "faqs_user_id_foreign":"users"."id" < "faqs"."user_id"

Ref "fees_user_id_foreign":"users"."id" < "fees"."user_id"

Ref "forms_user_id_foreign":"users"."id" < "forms"."user_id"

Ref "grade_systems_user_id_foreign":"users"."id" < "grade_systems"."user_id"

Ref "grades_user_id_foreign":"users"."id" < "grades"."user_id"

Ref "issued_books_user_id_foreign":"users"."id" < "issued_books"."user_id"

Ref "messages_user_id_foreign":"users"."id" < "messages"."user_id"

Ref "notices_user_id_foreign":"users"."id" < "notices"."user_id"

Ref "notifications_user_id_foreign":"users"."id" < "notifications"."user_id"

Ref "oauth_access_tokens_user_id_foreign":"users"."id" < "oauth_access_tokens"."user_id"

Ref "oauth_auth_codes_user_id_foreign":"users"."id" < "oauth_auth_codes"."user_id"

Ref "oauth_clients_user_id_foreign":"users"."id" < "oauth_clients"."user_id"

Ref "routines_user_id_foreign":"users"."id" < "routines"."user_id"

Ref "sections_user_id_foreign":"users"."id" < "sections"."user_id"

Ref "student_board_exams_user_id_foreign":"users"."id" < "student_board_exams"."user_id"

Ref "student_infos_user_id_foreign":"users"."id" < "student_infos"."user_id"

Ref "subscriptions_user_id_foreign":"users"."id" < "subscriptions"."user_id"

Ref "syllabuses_user_id_foreign":"users"."id" < "syllabuses"."user_id"
