Table ConfigurationDocument {
  Oid Int64 [primary key]
  DocumentName String
  DocumentVersionString String
  User String
  InstanceKey String
  CreationTime DateTime
  DocumentText String
  Version Binary
}

