Table  {
  XML string
  State SiteState
  Name String [primary key]
  Owner_FK String
  LastUpdated DateTime
  Language String
  Description String
  IsAdult Boolean
  RequiredDll String
}

Table  {
  Email String [primary key]
  Password String
  IsAdmin Boolean
}

Table  {
  Site_FK String
  Date DateTime
  Id Int32 [primary key]
  Message String
  Type ReportType
}

Table  {
  Name String [primary key]
  LastUpdated DateTime
  Owner_FK String
  MD5 String
}

