Table dbo.Customers {
  CustomerID String [primary key]
  CompanyName String
  ContactName String
  ContactTitle String
  Address String
  City String
  Region String
  PostalCode String
  Country String
  Phone String
  Fax String
}

Table dbo.Orders {
  OrderID Int32 [primary key]
  CustomerID String
  EmployeeID Int32
  OrderDate DateTime
  RequiredDate DateTime
  ShippedDate DateTime
  ShipVia Int32
  Freight Decimal
  ShipName String
  ShipAddress String
  ShipCity String
  ShipRegion String
  ShipPostalCode String
  ShipCountry String
  ShipAdress String
}

