Table dbo.Balances {
  Ticker String [primary key]
  Date DateTime [primary key]
  Period Char [primary key]
  Cash & Equivalents Decimal
  Short Term Investments Decimal
  Cash and Short Term Investments Decimal
  Accounts Receivable - Trade, Net Decimal
  Receivables - Other Decimal
  Total Receivables, Net Decimal
  Total Inventory Decimal
  Prepaid Expenses Decimal
  Other Current Assets, Total Decimal
  Total Current Assets Decimal
  Property/Plant/Equipment, Total - Gross Decimal
  Goodwill, Net Decimal
  Intangibles, Net Decimal
  Long Term Investments Decimal
  Other Long Term Assets, Total Decimal
  Total Assets Decimal
  Accounts Payable Decimal
  Accrued Expenses Decimal
  Notes Payable/Short Term Debt Decimal
  Current Port. of LT Debt/Capital Leases Decimal
  Other Current liabilities, Total Decimal
  Total Current Liabilities Decimal
  Long Term Debt Decimal
  Capital Lease Obligations Decimal
  Total Long Term Debt Decimal
  Total Debt Decimal
  Deferred Income Tax Decimal
  Minority Interest Decimal
  Other Liabilities, Total Decimal
  Total Liabilities Decimal
  Redeemable Preferred Stock, Total Decimal
  Preferred Stock - Non Redeemable, Net Decimal
  Common Stock, Total Decimal
  Additional Paid-In Capital Decimal
  Retained Earnings (Accumulated Deficit) Decimal
  Treasury Stock - Common Decimal
  Other Equity, Total Decimal
  Total Equity Decimal
  Total Liabilities & Shareholders' Equity Decimal
  Shares Outs - Common Stock Primary Issue Decimal
  Total Common Shares Outstanding Decimal
}

