Table dbo.carrot_FaqCategory {
  FaqCategoryID Guid [primary key]
  FAQTitle String
  SiteID Guid
}

Table dbo.carrot_FaqItem {
  FaqItemID Guid [primary key]
  FaqCategoryID Guid
  ItemOrder Int32
  IsActive Boolean
  Caption String
  Question String
  Answer String
}

