Table dbo.Branch {
  ID_Branch Int32 [primary key]
  Branch_Name String
  Degree String
}

Table dbo.Room_Type {
  Type_Name String [primary key]
}

Table dbo.Class {
  Class_ID Int32 [primary key]
  Course_ID Int32
  Practical_unit Int32
  Theory_unit Int32
  RoomType String
}

Table dbo.Classroom_Time {
  Room_ID Int32 [primary key]
  Class_ID Int32 [primary key]
  Professor_ID Int32
  StartTime Int32 [primary key]
  Duration Int16
  Day_No Int32 [primary key]
}

Table dbo.Course {
  Course_ID Int32 [primary key]
  Branch_ID Int32
  TermNo Int32
  Name_Course String
  Type_Course String
  CourseCode Decimal
  TheoryUnitNo Int32
  PracticalUnitNo Int32
  InRequisite_CourseID String
  PreRequisite_CourseID String
}

Table dbo.Group_ID_List {
  Group_ID Int32 [primary key]
  Class_ID Int32 [primary key]
}

Table dbo.Groups {
  ID Int32 [primary key]
  Semester_Entry_Year Int32
  Semester_Entry_FS Boolean
  Branch_Selection Int32
  Size_No Int32
}

Table dbo.New_GroupsPerClass {
  Room_ID Int32
  Class_ID Int32
  StartTime Int32
  Day_No Int32
  Group_ID Int32
}

Table dbo.Priority_Professor {
  Professor_ID Int32 [primary key]
  Class_ID Int32 [primary key]
  Priority Decimal
}

Table dbo.Professor {
  ID Int32 [primary key]
  Name_Professor String
  Branch String
  Email String
  EducationDegree String
  Schedule String
}

Table dbo.Room {
  Room_ID Int32 [primary key]
  Name_Room String
  Type_Room String
  Size_No Int32
}

