Table dbo.Company {
  Name String
  company_id Guid [primary key]
}

Table dbo.Department {
  Name String
  department_id Guid [primary key]
  company_id Guid
  parent_id Guid
}

Table dbo.Employee {
  Salary Decimal
  employee_id Guid [primary key]
  person_id Guid [primary key]
  department_id Guid [primary key]
  IsManager Boolean
}

Table dbo.Person {
  Name String
  Address String
  person_id Guid [primary key]
}

