Table dbo.AssignedProjectResource {
  ResourceId Guid [primary key]
  ProjectId Guid [primary key]
}

Table dbo.Plugin {
  PluginId Guid [primary key]
  Name String
  Version String
  UserId Guid
  DateCreated DateTime
  Hash Byte[]
}

Table dbo.RequiredPlugins {
  RequiredPluginId Guid [primary key]
  TaskId Guid
  PluginId Guid
}

Table dbo.Resource {
  ResourceId Guid [primary key]
  Name String
  ResourceType String
  ParentResourceId Guid
  HbInterval Int32
  OwnerUserId Guid
}

Table dbo.Task {
  TaskId Guid [primary key]
  TaskState TaskState
  ExecutionTimeMs Double
  LastHeartbeat DateTime
  ParentTaskId Guid
  Priority Int32
  CoresNeeded Int32
  MemoryNeeded Int32
  IsParentTask Boolean
  FinishWhenChildJobsFinished Boolean
  Command Command?
  JobId Guid
}

Table dbo.Downtime {
  DowntimeId Guid [primary key]
  ResourceId Guid
  StartDate DateTime
  EndDate DateTime
  AllDayEvent Boolean
  Recurring Boolean
  RecurringId Guid
  DowntimeType DowntimeType
}

Table dbo.Job {
  JobId Guid [primary key]
  Name String
  Description String
  OwnerUserId Guid
  DateCreated DateTime
  ProjectId Guid
  JobState JobState
}

Table dbo.TaskData {
  TaskId Guid [primary key]
  Data Byte[]
  LastUpdate DateTime
}

Table dbo.PluginData {
  PluginDataId Guid [primary key]
  PluginId Guid
  Data Byte[]
  FileName String
}

Table dbo.StateLog {
  StateLogId Guid [primary key]
  State TaskState
  DateTime DateTime
  TaskId Guid
  UserId Guid
  SlaveId Guid
  Exception String
}

Table dbo.JobPermission {
  JobId Guid [primary key]
  GrantedUserId Guid [primary key]
  GrantedByUserId Guid
  Permission Permission
}

Table  {
  LifecycleId Int32 [primary key]
  LastCleanup DateTime
}

Table  {
  UserId Guid [primary key]
  DateEnqueued DateTime
}

Table statistics.DimClient {
  Id Guid [primary key]
  Name String
  ResourceId Guid
  ParentResourceId Guid
  ResourceType String
  DateCreated DateTime
  DateExpired DateTime
}

Table statistics.FactTask {
  TaskId Guid [primary key]
  CalculatingTime Int64
  WaitingTime Int64
  TransferTime Int64
  NumCalculationRuns Int32
  NumRetries Int32
  CoresRequired Int32
  MemoryRequired Int32
  Priority Int32
  LastClientId Guid
  JobId Guid
  EndTime DateTime
  TaskState TaskState
  Exception String
  InitialWaitingTime Int64
  StartTime DateTime
}

Table statistics.DimJob {
  JobId Guid [primary key]
  UserId Guid
  JobName String
  UserName String
  DateCreated DateTime
  TotalTasks Int32
  CompletedTasks Int32
  DateCompleted DateTime
  ProjectId Guid
}

Table statistics.DimTime {
  Time DateTime [primary key]
  Hour DateTime
  Day DateTime
  Month DateTime
  Year DateTime
  Minute DateTime
}

Table statistics.DimUser {
  UserId Guid [primary key]
  Name String
}

Table statistics.FactClientInfo {
  ClientId Guid [primary key]
  Time DateTime [primary key]
  UserId Guid [primary key]
  NumUsedCores Int32
  NumTotalCores Int32
  UsedMemory Int32
  TotalMemory Int32
  CpuUtilization Double
  IdleTime Int64
  OfflineTime Int64
  UnavailableTime Int64
  SlaveState SlaveState
  IsAllowedToCalculate Boolean
}

Table dbo.Project {
  ProjectId Guid [primary key]
  ParentProjectId Guid
  DateCreated DateTime
  Name String
  Description String
  OwnerUserId Guid
  StartDate DateTime
  EndDate DateTime
}

Table dbo.ProjectPermission {
  ProjectId Guid [primary key]
  GrantedUserId Guid [primary key]
  GrantedByUserId Guid
}

Table dbo.AssignedJobResource {
  ResourceId Guid [primary key]
  JobId Guid [primary key]
}

Table statistics.FactProjectInfo {
  ProjectId Guid [primary key]
  Time DateTime [primary key]
  NumTotalCores Int32
  NumUsedCores Int32
  TotalMemory Int32
  UsedMemory Int32
}

Table statistics.DimProject {
  Id Guid [primary key]
  ProjectId Guid
  ParentProjectId Guid
  Name String
  Description String
  OwnerUserId Guid
  StartDate DateTime
  EndDate DateTime
  DateCreated DateTime
  DateExpired DateTime
}

