Table dbo.AlgorithmClass {
  Id Int64 [primary key]
  Name String
  Description String
}

Table dbo.ProblemClass {
  Id Int64 [primary key]
  Name String
  Description String
}

Table dbo.AlgorithmUser {
  AlgorithmId Int64 [primary key]
  UserGroupId Guid [primary key]
}

Table dbo.ProblemUser {
  ProblemId Int64 [primary key]
  UserGroupId Guid [primary key]
}

Table dbo.Platform {
  Id Int64 [primary key]
  Name String
  Description String
}

Table dbo.DataType {
  Id Int64 [primary key]
  Name String
  TypeName String
}

Table dbo.ValueName {
  Id Int64 [primary key]
  Name String
  Category ValueNameCategory
  Type ValueNameType
}

Table dbo.Algorithm {
  Id Int64 [primary key]
  AlgorithmClassId Int64
  PlatformId Int64
  DataTypeId Int64
  BinaryDataId Int64
  Name String
  Description String
}

Table dbo.Problem {
  Id Int64 [primary key]
  ProblemClassId Int64
  PlatformId Int64
  DataTypeId Int64
  BinaryDataId Int64
  Name String
  Description String
}

Table dbo.BinaryData {
  Id Int64 [primary key]
  Data Binary
  Hash Byte[]
}

Table dbo.Run {
  Id Int64 [primary key]
  AlgorithmId Int64
  ProblemId Int64
  CreatedDate DateTime
  UserId Guid
  ClientId Guid
}

Table dbo.Value {
  Id Int64 [primary key]
  RunId Int64
  ValueNameId Int64
  DataTypeId Int64
  BoolValue Boolean
  IntValue Int32
  LongValue Int64
  FloatValue Single
  DoubleValue Double
  StringValue String
  BinaryDataId Int64
}

Table dbo.Characteristic {
  Id Int64 [primary key]
  Name String
  Type CharacteristicType
}

Table dbo.CharacteristicValue {
  Id Int64 [primary key]
  ProblemId Int64
  CharacteristicId Int64
  DataTypeId Int64
  BoolValue Boolean
  IntValue Int32
  LongValue Int64
  FloatValue Single
  DoubleValue Double
  StringValue String
}

Table dbo.SingleObjectiveSolution {
  Id Int64 [primary key]
  ProblemId Int64
  BinaryDataId Int64
  RunId Int64
  Quality Double
  DataTypeId Int64
}

