Table dbo.Products {
  ProductID Int32 [primary key]
  ProductName String
  SupplierID Int32
  CategoryID Int32
  QuantityPerUnit String
  UnitPrice Decimal
  UnitsInStock Int16
  UnitsOnOrder Int16
  ReorderLevel Int16
  Discontinued Boolean
}

Table dbo.Categories {
  CategoryID Int32 [primary key]
  CategoryName String
  Description String
  Picture Binary
}

Table dbo.Suppliers {
  SupplierID Int32 [primary key]
  CompanyName String
  ContactName String
  ContactTitle String
  Address String
  City String
  Region String
  PostalCode String
  Country String
  Phone String
  Fax String
  HomePage String
}

Table dbo.Employees {
  EmployeeID Int32 [primary key]
  LastName String
  FirstName String
  Title String
  TitleOfCourtesy String
  BirthDate DateTime
  HireDate DateTime
  Address String
  City String
  Region String
  PostalCode String
  Country String
  HomePhone String
  Extension String
  Photo Binary
  Notes String
  ReportsTo Int32
  PhotoPath String
}

Table dbo.EmployeeTerritories {
  EmployeeID Int32 [primary key]
  TerritoryID String [primary key]
  Selected Boolean
}

Table dbo.Territories {
  TerritoryID String [primary key]
  TerritoryDescription String
  RegionID Int32
}

