Table dbo.tblGallery {
  GalleryID Guid [primary key]
  GalleryTitle String
  SiteID Guid
}

Table dbo.tblGalleryImageMeta {
  GalleryImageMetaID Guid [primary key]
  GalleryImage String
  ImageTitle String
  ImageMetaData String
  SiteID Guid
}

Table dbo.tblGalleryImage {
  GalleryImageID Guid [primary key]
  GalleryImage String
  ImageOrder Int32
  GalleryID Guid
}

