Table dbo.Story {
  Id Guid [primary key]
  UniqueName String
  Title String
  HtmlDescription String
  TextDescription String
  Url String
  UrlHash String
  CategoryId Guid
  UserId Guid
  IPAddress String
  CreatedAt DateTime
  LastActivityAt DateTime
  SpammedAt DateTime
  PublishedAt DateTime
  Rank Int32
  LastProcessedAt DateTime
  ApprovedAt DateTime
}

Table dbo.Tag {
  Id Guid [primary key]
  UniqueName String
  Name String
  CreatedAt DateTime
}

Table dbo.StoryTag {
  StoryId Guid [primary key]
  TagId Guid [primary key]
}

Table dbo.Category {
  Id Guid [primary key]
  UniqueName String
  Name String
  CreatedAt DateTime
}

Table dbo.StoryComment {
  Id Guid [primary key]
  HtmlBody String
  TextBody String
  CreatedAt DateTime
  StoryId Guid
  UserId Guid
  IPAddress String
  IsOffended Boolean
}

Table dbo.User {
  Id Guid [primary key]
  UserName String
  Password String
  Email String
  IsActive Boolean
  IsLockedOut Boolean
  Role Int32
  LastActivityAt DateTime
  CreatedAt DateTime
}

Table dbo.UserScore {
  Id Int64 [primary key]
  UserId Guid
  Timestamp DateTime
  ActionType Int32
  Score Decimal
}

Table dbo.UserTag {
  UserId Guid [primary key]
  TagId Guid [primary key]
}

Table dbo.StoryView {
  Id Int64 [primary key]
  StoryId Guid
  Timestamp DateTime
  IPAddress String
}

Table dbo.StoryVote {
  StoryId Guid [primary key]
  UserId Guid [primary key]
  IPAddress String
  Timestamp DateTime
}

