/* REFERENCES */

Table r_countries {
    id integer [pk]
    parent_id integer
    code varchar
    name varchar
}

Table r_cities {
    id integer [pk]
    parent_id integer
    country_id integer [ref: > r_countries.id]
    code varchar
    name varchar
}

Table r_water_types {
    // Финский залив, Ладожское озеро и т.п.
    id integer [pk]
    parent_id integer
    city_id integer [ref: > r_cities.id]
    name varchar
}

Table r_person_types {
    // Шейпер, Инструктор
    id integer [pk]
    parent_id integer
    code varchar
    name varchar
}

Table r_organisation_types {
    // Школа, Прокат
    id integer [pk]
    parent_id integer
    code varchar
    name varchar
}

Table r_place_types {
    // Город, Серф-спот
    id integer [pk]
    parent_id integer
    code varchar
    name varchar
}

Table r_notification_types {  // @TODO: fix this! This is not a ref, but a table. And we need ref and table
    id integer [pk]
    city_id integer [ref: > r_cities.id]
    parent_id integer
    code varchar
    title varchar
    main_text varchar
    overline varchar
}

Table r_communication_types {
    // Чат, канал
    id integer [pk]
    parent_id integer
    code varchar
    name varchar
}

Table r_spot_types {
    // Beach break, Point break, Reef break, Artificial wave
    id integer [pk]
    parent_id integer
    code varchar
    name varchar
}

Table r_wave_directions {
    // Left, Right, Left and Right
    id integer [pk]
    parent_id integer
    code varchar
    name varchar
}

Table r_spot_bottom_types {
    // Sand, Stones
    id integer [pk]
    parent_id integer
    code varchar
    name varchar
}

Table r_spot_threat_types {
    // Камни в воде, Сильные течения, 
    id integer [pk]
    parent_id integer
    code varchar
    name varchar
}

Table r_spot_crowd_levels {
    // Низкий, Средний, Высокий
    id integer [pk]
    parent_id integer
    code varchar
    name varchar
}

Table r_spot_difficulty_levels {
    // Начинающий, Продвинутый
    id integer [pk]
    parent_id integer
    code varchar
    name varchar
}

Table r_wave_qualities {
    // Низкое, Среднее, Высокое
    id integer [pk]
    parent_id integer
    code varchar
    name varchar
}

Table r_wind_directions {
    // N, NE, E, SE, S, SW, W, WN
    id integer [pk]
    parent_id integer
    code varchar
    name varchar
}

Table r_wave_types {
    // Swell, Wind, River, Atrificial
    id integer [pk]
    parent_id integer
    code varchar
    name varchar
}

Table r_contact_types {
    // Site, Social network, Messenger, Phone
    id integer [pk]
    parent_id integer
    code varchar
    name varchar
}


/* MAIN TABLES */

Table places {
    id integer [pk]
    city_id integer [ref: > r_cities.id]
    place_type_id integer [ref: > r_place_types.id]
    code varchar
    is_active boolean
    is_popular boolean
    name varchar
    summary varchar
    description varchar
}

Table persons {
    id integer [pk]
    person_type_id integer [ref: > r_person_types.id]
    code varchar
    name varchar
    summary varchar
    description varchar
}

Table communications {
    id integer [pk]
    city_id integer [ref: > r_cities.id]
    communication_type_id integer [ref: > r_communication_types.id]
    code varchar
    name varchar
    summary varchar
    description varchar
}

Table stores {
    id integer [pk]
    city_id integer [ref: > r_cities.id]
    code varchar
    name varchar
}

Table organisations {
    id integer [pk]
    organisation_type_id integer [ref: > r_organisation_types.id]
    code varchar
    name varchar
    summary varchar
    description varchar
}

Table workshops {
    id integer [pk]
    city_id integer [ref: > r_cities.id]
    code integer
    name integer
    summary varchar
    description varchar
}

Table spot_specification {
    id integer [pk]
    place_id integer [ref: > places.id]
    spot_type_id integer [ref: > r_spot_types.id]
    bottom_type_id integer [ref: > r_spot_bottom_types.id]
    difficulty_leve_id integer [ref: > r_spot_difficulty_levels.id]
    crowd_level_id integer [ref: > r_spot_crowd_levels.id]
    // Threats made as connections table
}

Table spot_wave_specification {
    id integer [pk]
    place_id integer [ref: > places.id]
    direction_id integer [ref: > r_wave_directions.id]
    quality_id integer [ref: > r_wave_qualities.id]
}

Table spot_pros {
    id integer [pk]
    spot_id integer [ref: > places.id]
    name varchar
}

Table spot_cons {
    id integer [pk]
    spot_id integer [ref: > places.id]
    name varchar
}

Table spot_notes {
    id integer [pk]
    spot_id integer [ref: > places.id]
    value varchar
}

Table spot_webcams {
    id integer [pk]
    spot_id integer [ref: > places.id]
    value varchar
}


/* CONNECTIONS */

Table persons_cities {
    id integer [pk]
    city_id integer [ref: > r_cities.id]
}

Table organisations_cities {
    id integer [pk]
    organisation_id integer [ref: > organisations.id]
    city_id integer [ref: > r_cities.id]
}

Table persons_organisations {
    id integer [pk]
    organisation_id integer [ref: > organisations.id]
}

Table persons_contacts {
    id integer [pk]
    person_id integer [ref: > persons.id]
    name varchar
    value varchar
}

Table workshops_contacts {
    id integer [pk]
    workshop_id integer [ref: > workshops.id]
    name varchar
    value varchar
}

Table stores_contacts {
    id integer [pk]
    store_id integer [ref: > stores.id]
    name varchar
    value varchar
}

Table spots_theats {
    id integer [pk]
    place_id integer [ref: > places.id]
    theat_id integer [ref: > r_spot_threat_types.id]
}


/* VIEWS */

Table view_spots {
    id integer [pk]
    is_active boolean
    is_popular boolean
    name varchar
    summary varchar
    description varchar
    spot_pros_id integer [ref: > spot_pros.id]
    spot_cons_id integer [ref: > spot_cons.id]
    spot_specification_id integer [ref: > spot_specification.id]
    spot_wave_specification_id integer [ref: > spot_wave_specification.id]
    // @TODO: continue. Decide how to get full view of the spot
}