Table dbo.BillDemandDistribution {
  Id Guid [primary key]
  BillDemandId Guid
  DemandId Guid
  ReserveId Guid
  OnDemand Boolean
  Sum Decimal
}

Table dbo.BillDemandDistributionOld {
  BillDemandId Guid
  ReserveId Guid
  ResrveWorkId Guid
  MonthId Byte
  Sum Decimal
}

Table dbo.BillDemandDistributionReserve {
  Id Guid [primary key]
  BillDemandDistributionId Guid
  DemandId Guid
  Sum Decimal
}

Table dbo.BillDemandDistributionReserveMoney {
  Id Guid [primary key]
  BillDemandDistributionReserveId Guid
  MonthId Byte
  Sum Decimal
}

Table dbo.BillDemandPath {
  Id Guid [primary key]
  BillDemandId Guid
  Path String
  FileName String
}

Table dbo.Reserve {
  Id Guid [primary key]
  Name String
  BudgetId Guid
  NumberId Int32
  ManagerId Guid
  CreatedDate DateTime
  Sum Decimal
  BankId Guid
  PlacedSum Decimal
  NDS Double
  SumWithoutNDS Decimal
}

Table dbo.Month {
  Id Byte [primary key]
  Name String
  Quarter Byte
}

Table dbo.SecurityTrusteeIdentity {
  Id Guid [primary key]
  TrusteeId Guid
  IdentityType Byte
  Login String
  PasswordMD5 Guid
}

Table dbo.WorkflowCurrentState {
  WorkflowId Guid [primary key]
  StateName String
  WorkflowTypeId Guid
}

Table dbo.WorkflowTrackingHistory {
  Id Guid [primary key]
  WorkflowId Guid
  StateName String
  TransitionTime DateTime
  WorkflowTypeId Guid
}

Table dbo.WorkflowType {
  Id Guid [primary key]
  Name String
}

Table dbo.StructDivision {
  Id Guid [primary key]
  ParentId Guid
  Name String
  SecurityGroupId Guid
  Code String
  hierarchicalCode Binary
  IsDeleted Boolean
  BudgetId Guid
  IsProtected Boolean
}

Table dbo.SecurityTrustee {
  Id Guid [primary key]
  Name String
  Description String
  IsContainer Boolean
  Enabled Boolean
}

Table dbo.SecurityDescriptorRecord {
  DescriptorId Guid
  TrusteeId Guid
  Id Guid [primary key]
  RoleId Guid
}

Table dbo.Currency {
  Id Guid [primary key]
  Name String
  Code String
  IsBase Boolean
  IsDeleted Boolean
}

Table dbo.CurrencyRate {
  CurrencyId Guid [primary key]
  RateDate DateTime [primary key]
  Rate Decimal
  RevRate Decimal
}

Table dbo.SecurityRole {
  Id Guid [primary key]
  Name String
}

Table dbo.SecurityGroup {
  TrusteeId Guid [primary key]
  ContainerId Guid [primary key]
}

Table dbo.BudgetVersion {
  Id Guid [primary key]
  Name String
  BudgetId Guid
  IsCurrent Boolean
}

Table dbo.Budget {
  Id Guid [primary key]
  Name Int32
  StatusId Byte
  Description String
  IsFrozen Boolean
  IsConfirm Boolean
}

Table dbo.BudgetStatus {
  Id Byte [primary key]
  Name String
}

Table dbo.Contact {
  Id Guid [primary key]
  Name String
  Fax String
  Phone String
  Email String
  Address String
  CountragentId Guid
  BudgetVersionId Guid
  IsDeleted Boolean
}

Table dbo.ContractAllocation {
  Id Guid [primary key]
  ContractId Guid
  AllocationId Guid
  Weight Double
}

Table dbo.ContractStatus {
  Id Byte [primary key]
  Name String
}

Table dbo.Limit {
  Id Guid [primary key]
  Name String
  Code String
  BudgetVersionId Guid
  ManagerId Guid
  ExecutorId Guid
  Sum Decimal
  TypeId Byte
  IsDeleted Boolean
}

Table dbo.DemandMoney {
  Id Guid [primary key]
  DemandId Guid
  MonthId Byte
  Sum Decimal
}

Table dbo.ExpertCostArticle {
  ExpertId Guid [primary key]
  CostArticleId Guid [primary key]
}

Table dbo.DeputyEmployee {
  Id Guid [primary key]
  CreateDate DateTime
  Employee Guid
  DeputyEmployee Guid
  StartDate DateTime
  EndDate DateTime
}

Table dbo.Expert {
  Id Guid [primary key]
  SecurityTrusteeId Guid
  BudgetId Guid
  Count Int32
  IsDeleted Boolean
}

Table dbo.CurrencyRateActual {
  CurrencyId Guid [primary key]
  Rate Decimal
  ReevaluationDate DateTime
}

Table dbo.DemandAllocation {
  Id Guid [primary key]
  DemandId Guid
  Weight Double
  CfoId Guid
  GeographicalPositionId Guid
}

Table dbo.AppSettings {
  Name String [primary key]
  Value String
}

Table dbo.EMailTemplates {
  Code String [primary key]
  Body String
  Head String
}

Table dbo.ContractMoney {
  Id Guid [primary key]
  ContractId Guid
  Year Int32
  MonthId Byte
  Sum Decimal
  PaidState Boolean
  ExternalFromEmployeeId Int32
  ExternaToEmployeeId Int32
  ConditionPayment String
  FromCounteragentId Guid
  ToCounteragentId Guid
  Date DateTime
  DateFrom DateTime
  DateTo DateTime
  Comment String
  Number String
  NumberId Int32
  ExternalId Int32
}

Table dbo.Project {
  Id Guid [primary key]
  Name String
  ParentId Guid
  Code String
  BudgetVersionId Guid
  IsDeleted Boolean
  IsProtected Boolean
  DateOpen DateTime
  DateClosed DateTime
  StateId Byte
  TypeId Byte
  ManagerEmployeeId Guid
  CodeVersion String
  Manager String
  StructDivisionId Guid
  Comment String
}

Table dbo.BillDemandAllocation {
  Id Guid [primary key]
  BillDemandId Guid
  CostArticleId Guid
  GoodsTypeId Guid
  ProjectId Guid
  Sum Decimal
  GeographicalPositionId Guid
  CfoId Guid
  CustomerId Guid
  FilialId Guid
}

Table dbo.CFO {
  Id Guid [primary key]
  Name String
  Code String
  ParentId Guid
  IsDeleted Boolean
  IsProtected Boolean
  DateOpen DateTime
  DateClosed DateTime
  FilialId Guid
  BlockId Guid
  Foundation String
  IsProviding Boolean
  OldId Guid
  BudgetId Guid
}

Table dbo.BillDemandContractMoney {
  Id Guid [primary key]
  Year Int32
  Month Byte
  Sum Decimal
  BillDemandId Guid
  ToPayment Boolean
  ContractMoneyId Guid
}

Table dbo.DemandPermission {
  CreateDate DateTime
  Id Guid [primary key]
  AuthorId Guid
  AuthorStructDivisionId Guid
  UserId Guid
  UserStructDivisionId Guid
  DemandId Guid
  EndPermissionDate DateTime
  IsRestricted Boolean
  IsConstantPermission Boolean
}

Table dbo.DemandTransitionHistory {
  Id Guid [primary key]
  TransitionTime DateTime
  Comment String
  TransitionInitiatorId Guid
  InitialStateId Byte
  DestinationStateId Byte
  DemandId Guid
  CommandId Guid
  TransitionExpectedInitiatorId Guid
  Description String
}

Table dbo.DemandAdjustmentTransitionHistory {
  Id Guid [primary key]
  TransitionTime DateTime
  Comment String
  TransitionInitiatorId Guid
  InitialStateId Byte
  DestinationStateId Byte
  DemandAdjustmentId Guid
  CommandId Guid
  TransitionExpectedInitiatorId Guid
  Description String
}

Table dbo.Contract {
  Id Guid [primary key]
  ParentId Guid
  Date DateTime
  Number String
  Subject String
  BudgetVersionId Guid
  CostArticleId Guid
  ProjectId Guid
  GoodsTypeId Guid
  IsActive Boolean
  InitiatorStructId Guid
  ExecutorStructId Guid
  BusinessBlockId Guid
  StatusId Byte
  DefenderId Guid
  IsDeleted Boolean
  Summ Decimal
  IsComplex Boolean
  DateFrom DateTime
  DateTo DateTime
  SolutionId Guid
  AuthorId Guid
  CurrencyId Guid
  CurrencySum Decimal
  ConditionPayment String
  BankId Guid
  NumberId Int64
  UnpaidMonth Int32
  CustomerId Guid
  DistributionDate DateTime
  NDS Double
  CurrencyRate Double
  CurrencyRateCBPercents Double
  CurrencyRateTypeId Byte
  ExternalId String
  ExternalCustomerId Int32
  ExternalExecutorId Int32
  ExternalCustomerDetails String
  ExternalExecutorDetails String
  ExternalManager String
  CustomerCounteragentId Guid
  ExecutorCounteragentId Guid
  AuthorStructDivisionId Guid
  Name String
  CounteragentId Guid
  HasDemand Boolean
  SumWithoutNDS Decimal
  IsProtected Boolean
  FilialId Guid
  CreateDate DateTime
  ChangedByID Guid
  ChangeDate DateTime
  IsPotential Boolean
}

Table dbo.Counteragent {
  Id Guid [primary key]
  ParentId Guid
  Name String
  BudgetVersionId Guid
  IsDeleted Boolean
  Number Int64
  Address String
  IsProtected Boolean
  ConfidentialAgreement Boolean
  AgreementDate DateTime
  INN String
  PersonalAccount String
  KPP String
  ContactInfo String
  Director String
  BankName String
  BankBIC String
  CurrencyId Guid
  CodeVersion String
  IsPotential Boolean
  FilialId Guid
  IdCft String
  AuthorID Guid
  CreateDate DateTime
  ChangedByID Guid
  ChangeDate DateTime
}

Table dbo.V_Report_BillDemand {
  Id Guid
  IdNumber Int64
  StateName String
  ContractNumber String
  ContractDate DateTime
  ContractName String
  Number String
  BudgetName Int32
  AccountDate DateTime
  Sum Decimal
  NDS Double
  NDSValue Decimal
  SumWithoutNDS Decimal
  CurrencyName String
  CurrencySum Decimal
  CurrencyRate Double
  CurrencyRateCBPercents Double
  CurrencyRateTypeId Byte
  AuthorName String
  DateOfPerformance DateTime
  AccountNumber String
  PaymentKindName String
  CounteragentName String
  PaymentFilialName String
  INN String
  KPP String
  PersonalAccount String
  BankName String
  BankBIC String
  Substance String
  DocKindName String
  IsCompensation Boolean
  Comment String
  CurrencyRateTypeParam String
  CurrencyRateTypeParamValue Double
  PaymentCurrency String
}

Table dbo.V_Report_BillDemandTransitionHistory {
  Id Guid
  BillDemandId Guid
  EmployeeName String
  TransitionTime DateTime
  CommandName String
  Comment String
  IsPlanTransition Boolean
}

Table dbo.V_Report_BillDemandAllocation {
  Id Guid
  BilldemandId Guid
  CostArticleCode String
  CostArticleName String
  CfoCode String
  CfoName String
  FilialName String
  Sum Decimal
}

Table dbo.V_Report_BillDemandDistribution {
  Id Guid
  BillDemandId Guid
  Number Int64
  CostArticleCode String
  CostArticleName String
  OPCode String
  OPName String
  ProjectCode String
  ProjectName String
  Sum Decimal
}

Table dbo.Employee {
  Id Guid [primary key]
  SecurityTrusteeId Guid
  StructDivisionId Guid
  BudgetId Guid
  EMail String
  IsDeleted Boolean
  IsProtected Boolean
  IsSendWorkflowNotification Boolean
}

Table dbo.WorkflowTickets {
  Id Guid [primary key]
  EntityId Guid
  IdentityId Guid
  ValidStateName String
  IsUsed Boolean
  ValidUntil DateTime
}

Table dbo.SecurityRoleRecord {
  RoleId Guid [primary key]
  PermissionId Guid [primary key]
  RecordType Byte
}

Table dbo.WorkflowSighting {
  Id Guid [primary key]
  EntityId Guid
  SighterId Guid
  SightingTime DateTime
  SightingType Byte
  ItemId Guid
  InitiatorId Guid
}

Table dbo.DemandAdjustment {
  Id Guid [primary key]
  BudgetId Guid
  IDNumber Int64
  Kind Byte
  Reason String
  CreatorId Guid
  State Byte
  IsWork Boolean
  SourceDemandId Guid
  TargetDemandId Guid
  Sum Decimal
  BillDemandId Guid
  AuthorStructDivisionId Guid
  IsPlanValue Boolean
  TypeId Byte
  IdNumberAuto Int64
  TransferDate DateTime
  AgreedDate DateTime
  OperationNumber Int32
}

Table dbo.BillDemandTransitionHistory {
  Id Guid [primary key]
  InitialStateId Byte
  DestinationStateId Byte
  BillDemandId Guid
  CommandId Guid
  TransitionInitiatorId Guid
  Comment String
  TransitionTime DateTime
  TransitionInitiatorStructDivisionId Guid
  TransitionExpectedInitiatorId Guid
  IsPlanTransition Boolean
  Description String
  TransitionTimeForSort DateTime
  SightingTime DateTime
}

Table dbo.DemandStatusInternal {
  Id Byte [primary key]
  Name String
  Order Byte
}

Table dbo.BillDemandState {
  Id Byte [primary key]
  Name String
  Order Byte
}

Table dbo.DemandAdjustmentState {
  Id Byte [primary key]
  Name String
  Order Byte
}

Table dbo.CostArticle {
  Id Guid [primary key]
  ParentId Guid
  Name String
  Code String
  BudgetVersionId Guid
  CodeVersion String
  IsDeleted Boolean
  Balance Char
  GroupCode String
  GroupName String
  B_KIND String
  KIND String
  IsProtected Boolean
  POS String
  CapOp String
  Comment String
  ExecutorId Guid
  ManagerId Guid
  ModifiedEmployeeId Guid
  ModifiedDate DateTime
  LimitId Guid
  AlwaysConfirmInGO Boolean
  AllowPlaningForPP Boolean
  AllowPlaningForFilial Boolean
  AllowPlaningForOP Boolean
  AllowPlaningForBusinessBlock Boolean
  AllowPlaningForChildCompany Boolean
  AlwaysConfirmInGOOnNormative Boolean
}

Table dbo.Demand {
  Id Guid [primary key]
  Description String
  CostArticleId Guid
  ProjectId Guid
  CounteragentId Guid
  GoodsTypeId Guid
  ExecutorId Guid
  DefenderId Guid
  IsActive Boolean
  InitiatorStructId Guid
  ExecutorStructId Guid
  BusinessBlockId Guid
  AuthorId Guid
  Number Int64
  WorkflowPositionId Guid
  NegativeEmployeeId Guid
  NegativeComment String
  BudgetVersionId Guid
  BeginDivisionId Guid
  IsFrozen Boolean
  Direction Byte
  ContractBased Boolean
  IsDeleted Boolean
  ITSystemId Guid
  Comment String
  CodeVersion String
  ManagerId Guid
  Generation Int32
  ActorId Guid
  IsPrincipal Boolean
  LeasingStatus Byte
  IsPlanned Boolean
  InternalStatusId Byte
  ExternalStatusId Byte
  Evolution Int32
  Name String
  HasAllocation Boolean
  CustomerId Guid
  BankId Guid
  NDS Double
  AuthorStructDivisionId Guid
  LimitId Guid
  CategoryExpensesId Guid
  DocKindId Byte
  IsUnionDemand Boolean
  UnionDemandId Guid
  IsNegative Boolean
  SumWithoutNDS Decimal
  CustomerCfoId Guid
  IsBlockCustomerCfo Boolean
  MultiAllocationName String
  MultiAllocationCode String
  DiscountQ1 Decimal
  DiscountQ2 Decimal
  DiscountQ3 Decimal
  DiscountQ4 Decimal
  StaffNormativeId Guid
  PayerFilialId Guid
  PlanningTypeId Byte
  StaffNormativeVersion Int32
  AgreementCfo Guid
  Version Int32
  MarginQ1 Decimal
  MarginQ2 Decimal
  MarginQ3 Decimal
  MarginQ4 Decimal
}

Table dbo.Filial {
  Id Guid [primary key]
  Name String
  Code String
  BudgetVersionId Guid
  IsDeleted Boolean
  IsProtected Boolean
  ParentId Guid
  IsBillDemandExportable Boolean
  IsSkipInAccountingState Boolean
}

Table dbo.vSecurityTrusteeRoles {
  Id Guid [primary key]
  RoleId Guid [primary key]
}

Table dbo.BillDemand {
  Id Guid [primary key]
  IdNumber Int64
  BudgetId Guid
  Number String
  Substance String
  CounteragentId Guid
  ContractId Guid
  Sum Decimal
  AllocationDate DateTime
  DateOfPerformance DateTime
  IsSFReceipt Boolean
  IsActReceipt Boolean
  IsBillReceivable Boolean
  BillDemandStateId Byte
  CurrencyId Guid
  CurrencySum Decimal
  AuthorId Guid
  TransferDate DateTime
  AccountDate DateTime
  AccountNumber String
  Comment String
  Condition String
  BankId Guid
  ITSystem Guid
  NDS Double
  CurrencyRate Double
  CurrencyRateCBPercents Double
  CurrencyRateTypeId Byte
  LimitManagerId Guid
  CuratorId Guid
  AuthorStructDivisionId Guid
  INN String
  PersonalAccount String
  KPP String
  BankName String
  BankBIC String
  DocKindId Byte
  CategoryExpensesId Guid
  PaymentKindId Byte
  FilialId Guid
  IsCompensation Boolean
  PaymentCurrencyId Guid
  MultiOPName String
  MultiOPCode String
  MultiPPName String
  MultiPPCode String
  MultiProjectName String
  MultiProjectCode String
  MultiCostArticleName String
  MultiCostArticleCode String
  ClassifiedOrder String
  SumWithoutNDS Decimal
  NDSValue Decimal
  IsNDSFixed Boolean
  MultiFilialName String
  BudgetPartId Byte
}

