Table dbo.Campaigns {
  CampaignID Int32 [primary key]
  Name String
  Value Int32
}

Table dbo.Events {
  EventID Int32 [primary key]
  Name String
  Slug String
  Start DateTime
  End DateTime
  HiFiveLimit Int32
}

Table dbo.Friendships {
  Befriender String [primary key]
  Befriendee String [primary key]
}

Table dbo.Points {
  PointID Int32 [primary key]
  Username String
  Issued DateTime
  Amount Int32
  Details String
}

Table dbo.Redemptions {
  RedemptionID Int32 [primary key]
  Username String
  TokenID Int32
  Created DateTime
}

Table dbo.TagAggregates {
  TagAggregateID Int32
  Tag String
  UserTypeID String
  Count Int32
}

Table dbo.Messages {
  Username String [primary key]
  Text String
  Offensive Boolean
}

Table dbo.Tags {
  Name String [primary key]
  Username String [primary key]
  Created DateTime
}

Table dbo.TideMarks {
  TideMarkID Int32 [primary key]
  Name String
  LastID Int64
  TimeStamp DateTime
}

Table dbo.Sats {
  Username String [primary key]
  SessionID Int32 [primary key]
  SeatID Int32
}

Table dbo.Sessions {
  SessionID Int32 [primary key]
  EventID Int32
  Name String
  Start DateTime
  Finish DateTime
}

Table dbo.HiFives {
  HiFiveID Int32 [primary key]
  HiFiver String
  HiFivee String
  EventID Int32
}

Table dbo.Tokens {
  TokenID Int32 [primary key]
  CampaignID Int32
  Code String
  AllowedRedemptions Int32
  FileName String
  Text String
}

Table dbo.Seats {
  SeatID Int32 [primary key]
  Row Int32
  Column Int32
  EventID Int32
  Code String
}

Table dbo.UserTypes {
  UserTypeID String [primary key]
  Name String
  Ordering Int32
  DefaultColour String
  BurningColour String
  HotColour String
  WarmColour String
}

Table dbo.QueuedTweets {
  QueuedTweetID Int32 [primary key]
  Username String
  Message String
  Created DateTime
  Processed Boolean
  ImageURL String
  Followers Int32
  FullName String
}

Table dbo.Users {
  Username String [primary key]
  ImageURL String
  Created DateTime
  Updated DateTime
  UserTypeID String
  ShadowAccount Boolean
  Followers Int32
  FullName String
}

