Table Categories {
  Category ID Int32 [primary key]
  Category Name String
  Description String
  Picture Binary
}

Table Customers {
  Customer ID String [primary key]
  Company Name String
  Contact Name String
  Contact Title String
  Address String
  City String
  Region String
  Postal Code String
  Country String
  Phone String
  Fax String
}

Table Employees {
  Employee ID Int32 [primary key]
  Last Name String
  First Name String
  Title String
  Birth Date DateTime
  Hire Date DateTime
  Address String
  City String
  Region String
  Postal Code String
  Country String
  Home Phone String
  Extension String
  Photo Binary
  Notes String
  Reports To Int32
}

Table Order Details {
  Order ID Int32 [primary key]
  Product ID Int32 [primary key]
  Unit Price Decimal
  Quantity Int16
  Discount Single
}

Table Orders {
  Order ID Int32 [primary key]
  Customer ID String
  Employee ID Int32
  Ship Name String
  Ship Address String
  Ship City String
  Ship Region String
  Ship Postal Code String
  Ship Country String
  Ship Via Int32
  Order Date DateTime
  Required Date DateTime
  Shipped Date DateTime
  Freight Decimal
}

Table Products {
  Product ID Int32 [primary key]
  Supplier ID Int32
  Category ID Int32
  Product Name String
  English Name String
  Quantity Per Unit String
  Unit Price Decimal
  Units In Stock Int16
  Units On Order Int16
  Reorder Level Int16
  Discontinued Boolean
}

Table Shippers {
  Shipper ID Int32 [primary key]
  Company Name String
}

Table Suppliers {
  Supplier ID Int32 [primary key]
  Company Name String
  Contact Name String
  Contact Title String
  Address String
  City String
  Region String
  Postal Code String
  Country String
  Phone String
  Fax String
}

