Table Accounts {
  AccountID Int32 [primary key]
  OpenBalance Decimal
  CreationDate DateTime
  Users_UserID Int32
  CashBalance Decimal
  AssetBalance Decimal
  AccountName String
}

Table HistoricalQuotes {
  QuoteID Int32 [primary key]
  Symbol String
  Date DateTime
  Open Decimal
  High Decimal
  Low Decimal
  Close Decimal
  Volume Int64
}

Table Holdings {
  HoldingID Int32 [primary key]
  Quotes_Symbol String
  Quantity Decimal
  PricePaid Decimal
  PurchaseDate DateTime
  Accounts_AccountID Int32
  StockExchangeID Int32
  Open Boolean
}

Table Industries {
  IndustryID Int32 [primary key]
  IndusrtyName String
  SectorID Int32
}

Table Quotes {
  Symbol String [primary key]
  CompanyName String
  Price Decimal
  Change Double
  % Change Double
  Open Decimal
  High Decimal
  Low Decimal
  Volume Double
  Industry_IndustryID Int32
}

Table Sectors {
  SectorID Int32 [primary key]
  SectorName String
}

Table StockExchanges {
  StockExchangeID Int32 [primary key]
  StockExchangeName String
  Country String
}

